### ISSUE TITLE
404 error using express app as exported function

### ISSUE THREAD

**Issue by lukesammy** [firebase/firebase-functions#720] opened 2020-06-27 14:55 UTC
### Related issues

https://github.com/firebase/functions-samples/issues/555#issue-comment-box

### [REQUIRED] Version info

3.3.0

**node:**

8.0.0

**firebase-functions:**

**firebase-tools:**

7.14.0

**firebase-admin:**

### [REQUIRED] Steps to reproduce

Running the example provided here (https://firebase.google.com/docs/functions/http-events):

```javascript
const express = require('express');
const cors = require('cors');

const app = express();

// Automatically allow cross-origin requests
app.use(cors({ origin: true }));

// Add middleware to authenticate requests
app.use(myMiddleware);

// build multiple CRUD interfaces:
app.get('/:id', (req, res) => res.send(Widgets.getById(req.params.id)));
app.post('/', (req, res) => res.send(Widgets.create()));
app.put('/:id', (req, res) => res.send(Widgets.update(req.params.id, req.body)));
app.delete('/:id', (req, res) => res.send(Widgets.delete(req.params.id)));
app.get('/', (req, res) => res.send(Widgets.list()));

// Expose Express API as a single Cloud Function:
exports.widgets = functions.https.onRequest(app);
```

### [REQUIRED] Expected behavior

This should work
```
https://us-central1-<project-id>.cloudfunctions.net/widgets/<id>
```

### [REQUIRED] Actual behavior

Gets 404 returned

Adding `/widgets` in front of each route then allows it to work

### Were you able to successfully deploy your functions?

Deployed successfully

**Comment by mbleigh** [comment] 2020-06-29 17:42
Hi, can you try deploying this again and see if you're still experiencing the same issue? We're trying to identify  whether this might have been caused by a rollout. Thanks!

**Comment by lukesammy** [comment] 2020-06-29 18:02
Hi @mbleigh, yeah looks like its working again! It seems like it wasn't working from Friday morning, and started working again Saturday morning (UTC+1). Let me know if there is anything I can do to help you identify the issue. Thanks

**Comment by samtstern** [comment] 2020-07-16 12:57
@lukesammy sounds like this is resolved for you, so closing this issue

**Closed by samtstern** 2020-07-16 12:57 UTC
Labels: api: http
