### ISSUE TITLE
[Error] V2 functions deployment fails with error in cloud run container service container fails to start

### ISSUE THREAD

**Issue by algoflows** [firebase/firebase-functions#1131] opened 2022-06-02 00:22 UTC
**node:** 

16

**firebase-functions:**

 3.21.2

**firebase-tools:** 

v11.0.1

**firebase-admin:**

**Steps to reproduce**

Deploying a single v2 firebase cloud function

```javascript
// FIREBASE V2 FUNCTION
const { onRequest } = require("firebase-functions/v2/https");

module.exports = onRequest(
  { timeoutSeconds: 1200, region: ["europe-west1"] },
  (_req, res) => {
    res.status(200).send("OK");
  }
);
```

**Expected behavior**

Deploy the gen2 firebase cloud function successefully and error free

**Actual behavior**

Deployment fails, v2 functions are unusable as they simply don't deploy.

<img width="303" alt="Screenshot 2022-06-02 at 01 18 34" src="https://user-images.githubusercontent.com/65465380/171522255-f44003ba-96ea-447b-8cd6-eaed6171ad3d.png">

### Were you able to successfully deploy your functions? 

**NO**

run > firebase deploy --only functions:function-name

result: 
<img width="585" alt="Screenshot 2022-06-02 at 01 17 26" src="https://user-images.githubusercontent.com/65465380/171522155-ebdb8354-3b79-4330-b318-d3e8025d0c0d.png">

```
❯ firebase deploy --only functions:webhooks-aifi-v2-checkout

=== Deploying to 'cornershop-app'...

i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/seank/Projects/capgemini/cornershop-app/functions (55.5 MB) for uploading
i  functions: packaged /Users/seank/Projects/capgemini/cornershop-app/functions (55.5 MB) for uploading
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
✔  functions: required API cloudscheduler.googleapis.com is enabled
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
✔  functions: required API eventarc.googleapis.com is enabled
✔  functions: required API run.googleapis.com is enabled
✔  functions: required API pubsub.googleapis.com is enabled
✔  functions: required API storage.googleapis.com is enabled
✔  functions: required API artifactregistry.googleapis.com is enabled
i  functions: generating the service identity for pubsub.googleapis.com...
i  functions: generating the service identity for eventarc.googleapis.com...
✔  functions: functions folder uploaded successfully
i  functions: creating Node.js 16 function webhooks-aifi-v2-checkout(europe-west1)...
Could not create or update Cloud Run service webhooks-aifi-v2-checkout, Container Healthcheck failed. Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=cornershop-app&resource=cloud_run_revision/service_name/webhooks-aifi-v2-checkout/revision_name/webhooks-aifi-v2-checkout-00001-qur&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22webhooks-aifi-v2-checkout%22%0Aresource.labels.revision_name%3D%22webhooks-aifi-v2-checkout-00001-qur%22
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start

Functions deploy had errors with the following functions:
        webhooks-aifi-v2-checkout(europe-west1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
```

<img width="795" alt="Screenshot 2022-06-02 at 01 21 31" src="https://user-images.githubusercontent.com/65465380/171522530-9c1fbfd3-0dd0-4f2c-8a6f-79c35fb553d3.png">

**Comment by gustavopch** [comment] 2022-06-07 20:35
Same issue happened here. I'm using a MacBook Pro M1 and [this page](https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start) says:

> Note: If you build your container image on a ARM based machine, then it might not work as expected when used with Cloud Run.

So I guess I'll have to stick with Functions v1 for now.

Source code:
```
import { onRequest } from 'firebase-functions/v2/https'

export const helloworld = onRequest(
  {
    region: 'us-east1',
  },
  (request, response) => {
    response.status(200).send({ hello: 'world' })
  },
)
```

Output when deploying:
```
i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
✔  functions: required API eventarc.googleapis.com is enabled
✔  functions: required API artifactregistry.googleapis.com is enabled
✔  functions: required API run.googleapis.com is enabled
✔  functions: required API storage.googleapis.com is enabled
✔  functions: required API pubsub.googleapis.com is enabled
i  functions: preparing ./build/functions directory for uploading...
i  functions: packaged ./build/functions (56.65 KB) for uploading
i  functions: packaged ./build/functions (55.54 KB) for uploading
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
✔  functions: required API cloudscheduler.googleapis.com is enabled
✔  functions: ./build/functions folder uploaded successfully
i  functions: creating Node.js 16 function helloworld(us-east1)...

Functions deploy had errors with the following functions:
        helloworld(us-east1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
error Command failed with exit code 2.
```

Google Cloud Logging:
```
Could not create or update Cloud Run service helloworld, Container Healthcheck failed. Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.
```

**Comment by algoflows** [comment] 2022-06-07 20:48
@gustavopch It's wild considering how many companies and users use firebase functions. Would have thought someone from the team at google would have at least replied by now.

**Comment by gustavopch** [comment] 2022-06-07 20:59
@algoflows Yeah, 6 days already. I know v2 is not under global availability and SLA, but still...

**Comment by algoflows** [comment] 2022-06-17 22:56
@firebase-ops anyone on the dev team going to support this issue? Any news, updates or feedback?

**Comment by paul-paliychuk** [comment] 2022-06-27 22:25
Also happened to me on intel chip

**Comment by mehdi-abbad** [comment] 2022-07-05 06:56
I stumbled upon the same issue as @algoflows and after rereading the logs a couple of times, it occurred to me that I was getting the configuration of the function by calling the `functions.config` which is not supported in functions v2. The error message is pretty clear on that:

```
Detailed stack trace: Error: functions.config() is no longer available
in Cloud Functions for Firebase v2. Please see the latest documentation
for information on how to transition to using environment variables
```

I hope this helps.

**Comment by taeold** [comment] 2022-07-12 01:06
Hi. I'm sorry I missed this issue.

I re-read the issue thread, and common issue I see is that there are, to one degree or another, some initialization code that contribute to container instance not starting properly on cloud run.

For example, I can replicate the issue 

Note that this isn't chip dependent - the container image deployed to Google Cloud Functions v2 is built on Cloud Build and is not affected by your development machine. Here's an example:

```
const functions = require("firebase-functions");
const { onRequest } = require("firebase-functions/v2/https");


const foo = functions.config("hello") // This will throw a runtime error on v2

module.exports = onRequest(
  { timeoutSeconds: 1200, region: ["europe-west1"] },
  (_req, res) => {
    res.status(200).send("OK");
  }
);
```

Note the use of `functions.config` - we do not support using functions config in v2 environment. Instead, we recommend that you use environment variables (https://firebase.google.com/docs/functions/config-env).

That being said, this is a very bad footgun. I will brainstorm with the team how we can improve the error message so that it's clear exactly what's going on during a function deploy.

**Comment by algoflows** [comment] 2022-07-12 09:56
Legendary, and thanks for the response. Will investigate migrating from functions config to env vars as suggested. 

Yes agree, clearer error messages would go a long way in helping isolate the issue 👍🏻

**Comment by clementdevos** [comment] 2022-07-18 15:52
Hi, 

I've just stumbled upon this issue while trying to use both v1 and v2 functions in the same repository. 
It might be bad code design but as  deploying a functions packs the whole repository, it crashes upon functions loading. 

This is the code that crashes our deployment. 

```
import * as AlgoliaClient from 'algoliasearch';
import * as functions from 'firebase-functions';

console.log('init algolia', functions.config().algolia.app_id);
export const algolia = AlgoliaClient(functions.config().algolia.app_id, functions.config().algolia.sk, {
    timeouts: {
        connect: 8 * 1000,
        read: 100 * 1000,
        write: 60 * 1000
    }
});
```

The documentation here (https://firebase.google.com/docs/functions/config-env#environment_configuration ) is not clear about the fact that functions.config() used somewhere in v2 function environment will crash with this message  (https://github.com/firebase/firebase-functions/pull/930)

We'll update the code to make it work then !

**Comment by taeold** [comment] 2022-07-18 19:09
Closing the issue as I think the original issue has been identified and resolved.

**Closed by taeold** 2022-07-18 19:09 UTC
Labels: needs-triage, Needs: Attention

**Comment by jonas-ecoverse** [comment] 2022-10-26 17:42
I got the same issue although I used v2 functions env reference like this.
![image](https://user-images.githubusercontent.com/114514569/198097816-1ca0a557-bddf-4a27-a16f-a6afd603478f.png)
But I am not sure if it is because we have v1 and v2 in one repo.
@taeold , having v1 and v2 together in one repo will impact that issue?

**Comment by taishi55** [comment] 2022-10-27 20:43
I got the same issue with custom event handlers. Still I have no idea to solve it. 

```
import { onCustomEventPublished } from "firebase-functions/v2/eventarc";

export const func = onCustomEventPublished(
    {
      eventType: "firebase.extensions.storage-resize-images.v1.complete",
      channel: "locations/us-west1/channels/firebase",
      region: "us-west1",
    },
    (event) => { ... });
```

**Comment by taishi55** [comment] 2022-10-27 21:16
@jonas-ecoverse 

It seems like V2 and V1 functions cannot be deployed together. 

On the documentation, I cannot find Cloud Firestore triggers for V2. 
I attempted to convert all of my V1 functions to V2 for the successful deployment.
However, V2 might not support Cloud Firestore triggers, I guess.

**Comment by taishi55** [comment] 2022-10-27 23:18
replace your `functions.config()` with `process.env` 🥳

and use secrets with `.env` file (you can do this by `firebase functions:config:export`)

**Comment by matija2209** [comment] 2023-05-31 15:26
I'm having the same issues.

I'm using params to define variables which I access with `process.env.BACKEND_ADDRESS`.
```
const { defineString } = require('firebase-functions/params');
const BACKEND_ADDRESS = defineString('BACKEND_ADDRESS');
```

I continue to receive the same error no matter what.

_Could not create or update Cloud Run service add-document, Container Healthcheck failed. Revision 'add-document-00003-mep' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable._

**Comment by Blunderchips** [comment] 2023-08-08 11:22
> I'm having the same issue.
> 
> I'm using params to define variables which I access with `process.env.BACKEND_ADDRESS`.
> 
> ```
> const { defineString } = require('firebase-functions/params');
> const BACKEND_ADDRESS = defineString('BACKEND_ADDRESS');
> ```
> 
> I continue to receive the same error no matter what.
> 
> _Could not create or update Cloud Run service add-document, Container Healthcheck failed. Revision 'add-document-00003-mep' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable._
> 
> The code works locally just fine.

Also getting this error, we have not changed any of the default config.

**Comment by asoomar** [comment] 2023-08-16 04:15
I'm also getting the same error. I am not using firebase.config but a .env file. Runs completely fine locally

**Comment by matija2209** [comment] 2023-08-16 11:32
@asoomar if you're running functions make sure that your deploy script in `package.json` has a -`-only-functions` flag.

`"deploy": "firebase deploy --only functions"`

**Comment by asoomar** [comment] 2023-08-20 04:16
@matija2209 I checked for this and it already had `"deploy": "firebase deploy --only functions"`. I was able to fix the error by using gen 1 firestore trigger instead of gen 2. I read in another issue that for some reason functions that are deployed to `Central1` do not work with gen 2 triggers.

**Comment by Blunderchips** [comment] 2023-08-20 07:16
All I am getting from this issue is that firebase functions gen 2 is not ready for production.

**Comment by BilalAtique** [comment] 2023-12-12 11:09
I was not using config(), so the above solution does not apply to me. What worked for me was deleting the lib function and deploying again.

**Comment by umrashrf** [comment] 2024-02-03 06:17
At Riamuapp.com, I was using V1 onCall functions and firebase.config() was working fine but as soon as I added V2 functions to an existing file containing V1 functions to keep backward compatibility, I got this error. But I changed my code to use dotenv module and fall back to function.config in case dotenv doesn't work.

**Comment by LipJ01** [comment] 2024-03-25 22:28
If index.ts is V2 then any V1 functions using firebase.config() will prevent all V2 functions from deploying.

[or so it would seem on my firebase project today]

**Comment by Naeem113** [comment] 2024-06-06 20:35
> I stumbled upon the same issue as @algoflows and after rereading the logs a couple of times, it occurred to me that I was getting the configuration of the function by calling `functions.config` which is not supported in functions v2. The error message is pretty clear on that:
> 
> ```
> Detailed stack trace: Error: functions.config() is no longer available
> in Cloud Functions for Firebase v2. Please see the latest documentation
> for information on how to transition to using environment variables
> ```
> 
> I hope this helps.

Thanks it works for me

**Comment by nickjuntilla** [comment] 2024-07-10 04:10
Wow this is awful. It's July 10 2024 and I've spent the last 24 hours on this trying to upgrade a project. Not only is the error message completely misleading:

" Could not create or update Cloud Run service test, Container Healthcheck failed. Revision 'test-00001-dah' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information."

The error has nothing to do with a container or a port. It also says NOWHERE in the docs that using functions.config anywhere OUTSIDE of the v2 function will still cause deployment to fail... ?!?!? This is what you guys say:

https://firebase.google.com/docs/functions/2nd-gen-upgrade
"2nd gen functions drop support for functions.config in favor of a more secure interface for [defining configuration parameters declaratively](https://firebase.google.com/docs/functions/config-env?gen=2nd#params) inside your codebase. With the new params module, the CLI blocks deployment unless all parameters have a valid value, ensuring that a function isn't deployed with missing configuration."

This heavily implies that we should not use functions.config inside of v2 functions. How on Earth would we know that we also can't use functions.config OUTSIDE of the v2 functions? 

It took me many hours to find this thread. Now I have to go refactor my entire (very large) project to change the configuration style in the entire thing before I can finally test if I can deploy a v2 function finally. It is very misleading for you guys to make it seem like we can migrate over one function at a time, when in fact trying to do this leads to this undocumented error. I've always been a huge proponent of firebase, but this is the kind of thing that makes people look for alternatives. 

Please consider a note on your migration page. https://firebase.google.com/docs/functions/2nd-gen-upgrade

**Comment by NNN-kakimoto** [comment] 2024-09-06 03:06
I also reproduced it. (nodejs22, express.js, typescript)
I originally thought I was running on functions gen1 and had migrated to gen2, but in fact the deployment was failing.
I quit importing from firebase-functions/v1.
```diff
// from
- import { logger } from 'firebase-functions/v1';
- import * as logger from 'firebase-functions/logger';
// to
+ import { logger } from 'firebase-functions/v2';
```
Deployment now succeeds.
I note this in case it helps anyone.
(Machine translation JP-EN)

**Comment by Flucadetena** [comment] 2024-11-13 20:53
I solve the problem by creating a new folder of functions inside the repo called "functions-v2", did firebase init inside and it walks you through the configuration for having two code spaces in the same repo and deploying them independently.

So you don't get ask If you would like to delete the functions from the other folder each time.

This is explained [here](https://firebase.google.com/docs/functions/organize-functions?gen=2nd#managing_multiple_source_packages_monorepo)

This way you can migrate your functions one at a time without having the "functions.config()" issue.

Hope it helps.

**Comment by jeremyfrancis** [comment] 2025-01-22 23:01
**MY SOLUTION**

My cloud-functions directory were a subdirectory of another project that included a package.json and yarn.lock file.  So when I would run "yarn install" it would install the modules but show some errors.

Turns out it was not generating the yarn.lock file and this was crucial.  (Or package-lock.json with npm)

This caused weird issues as a result...

So I took my cloud-functions folder and moved it to my desktop so there was no package.json as a parent, and ran "yarn install" there and it worked with no errors and generated the yarn.lock

I also deleted the "lib" folder to make a brand new build before doing "yarn install".

Once I went to redeploy it all worked fine.

**STEPS:**

1. Move cloud functions folder somewhere else like your Desktop
2. Remove node_modules, lib, package-lock.json and yarn.lock
3. Run "npm install" or "yarn install"
4. You can place the folder back to its original location
**5. Then deploy cloud functions successfully!** 

Hope this helps someone

**Comment by JiseungHong** [comment] 2025-02-07 05:31
For whom using some kind of:
```
const config = functions.config().githubapp || {};
const WEBHOOK_SECRET = config.webhook_secret || "";
```

I just changed into env:
`const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET || "";`

and worked.

**Comment by ttarinov** [comment] 2025-02-10 22:00
I found the solution. None of the recommendations from this thread worked for me.

I had the same problem, specifically when adding an `onRequest` function while using TypeScript. The issue occurs when importing both `onCall` and `onRequest` in the same line.

Looking at the compiled `index.js`, I noticed that TypeScript creates two separate imports:
```
const https_1 = require("firebase-functions/v2/https");
const https_2 = require("firebase-functions/v2/https");
```

To fix this, instead of importing both in one line:
```
import { onCall, onRequest } from "firebase-functions/v2/https";
```

Separate the imports in your `index.ts`:
```
import { onCall } from "firebase-functions/v2/https";
import { onRequest } from "firebase-functions/v2/https";
```
