### ISSUE TITLE
AppCheck is stopping callable execution even when "disabled"

### ISSUE THREAD

**Issue by nwparker** [firebase/firebase-functions#967] opened 2021-09-02 03:50 UTC
### Related issues

  * https://stackoverflow.com/questions/68386179/app-check-unwanted-enforcement-on-firebase-callable-functions
  * https://github.com/firebase/firebase-functions/pull/885

### [REQUIRED] Version info

**node:**
v14.17.0

**firebase-functions:**
3.15.5

**firebase-tools:**
latest

**firebase-admin:**
9.11.1

### [REQUIRED] Test case
```javascript
exports.yourCallableFunction = functions.https.onCall((data, context) => {
  console.log("Hello World");
});
```

### [REQUIRED] Steps to reproduce

1. Make a request to any callable with an **invalid** app token
   * _I'm making the call from iOS [App Attest]_

### [REQUIRED] Expected behavior

The above code should print "Hello World"

According to the documentation here (https://firebase.google.com/docs/app-check/cloud-functions), app check should only be enforced in the following manner:
```javascript
exports.yourCallableFunction = functions.https.onCall((data, context) => {
  // context.app will be undefined if the request doesn't include a valid
  // App Check token.
  if (context.app == undefined) {
    throw new functions.https.HttpsError(
        'failed-precondition',
        'The function must be called from an App Check verified app.')
  }

  // Your function logic follows.
});
````

Unfortunately, this not the case (it looks like this PR might have introduced this issue: https://github.com/firebase/firebase-functions/pull/885)

### [REQUIRED] Actual behavior

The above code does not print hello world. Instead it throws:
```
Failed to validate AppCheck token. FirebaseAppCheckError: Decoding App Check token failed. Make sure you passed the entire string JWT which represents the Firebase App Check token.
```

### Were you able to successfully deploy your functions?

Yes

**Comment by taeold** [comment] 2021-09-02 04:59
@nwparker This is intentional - see https://firebase.google.com/docs/functions/callable-reference#request_format_headers.

Verification of AppCheck token happens automatically in `onCall` functions, just as verification of auth tokens are done automatically.

To put it another way:

1. If `X-Firebase-AppCheck` header is missing, `context.app === undefined`.
2. If `X-Firebase-AppCheck` header contains an invalid token, `onCall` returns immediately with a 403.
3. If `X-Firebase-AppCheck` header contains a valid token, `context.app` is filled in with corresponding decoded token info.

While intentional, you are not the first user who finds this behavior confusing (see https://github.com/FirebaseExtended/flutterfire/issues/6794#issuecomment-897129319). Internally, we are discussing some changes - stay tuned.

**Comment by ipuris** [comment] 2021-10-06 11:36
I suffered a similar problem that a Firebase Function call from iOS and Android results in the immediate rejection. 
I checked both of this thread and https://github.com/FirebaseExtended/flutterfire/issues/6794, and the reason of my problem may be invalid token due to the improper configuration of AppCheck.
I decide to disable AppCheck and expect this change can fix my issue.

I have a question to clarify how `onCall()` exactly method works now and any planned changes, because because it seems there is a difference between this thread and the thread above. 

According to https://github.com/FirebaseExtended/flutterfire/issues/6794#issuecomment-903845907, 

> after some discussion we agreed to apply the following fixes:
> - Callable Functions implementation will be updated to handle an empty and invalid Firebase App Check token in the same way. onCall will be called with context.app == undefined for both cases, so control of enforcement of App Check will be in the function body only (basically as it is described in the docs)

and it seems that those changes are already applied in the latest version.

But you said that: 

> 2. If X-Firebase-AppCheck header contains an invalid token, onCall returns immediately with a 403.

It looks the changes are not applied yet.
Which one is right? Or do I have any misunderstanding?

**Comment by taeold** [comment] 2021-10-07 17:09
@ipuris The feature for handling empty and invalid app check token in the same way (as referenced in https://github.com/FirebaseExtended/flutterfire/issues/6794#issuecomment-903845907) hasn't landed in Firebase Functions SDK yet. So what I said above:

> If X-Firebase-AppCheck header contains an invalid token, onCall returns immediately with a 403.

Still is the behavior of the Functions SDK.

We are close though - https://github.com/firebase/firebase-functions/pull/986 is under review and once merge will offer a way to prevent enforcing App Check at the SDK level.

**Comment by taeold** [comment] 2022-02-23 19:57
Closing. The issue is addressed in https://github.com/firebase/firebase-functions/pull/989.

**Closed by taeold** 2022-02-23 19:57 UTC
Labels: type: feature request, api: http, tracked internally
