### ISSUE TITLE
Cloud Function Pub/Sub 429 and cron 500 no instance errors started on August 24

### ISSUE THREAD

**Issue by dgobaud** [firebase/firebase-functions#965] opened 2021-08-31 15:02 UTC
Starting August 24 our Pub/Sub and Cron cloud functions started generating a flood of 429 and 500 errors. We don't believe any code changed on our side to cause this.

Google Support case 28781796 doesn't seem to know what is wrong.

1. example cron below runs 4 times a day generates 500 error "The request was aborted because there was no available instance." when running

This doesn't make sense - it is starting up from the cron there isn't going to be an instance. It seems to run without a problem but it generates the error triggering our log alerts.

export const EmailPendingAccounts = functions
  .runWith({
    timeoutSeconds: 540,
    memory: '2GB',
    vpcConnector: 'fes-redis',
    vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY'
  })
  .pubsub.schedule('0 8,12,16,23 * * *')
  .timeZone('America/New_York')
  .onRun(async (context: functions.EventContext) => {

2021-08-30 05:00:12.324 PDT
POST
500
0 B
0 ms
CloudPubSub-Google
https://STUFF.appspot.com/_ah/push-handlers/pubsub/projects/passfolio-frontend-production/topics/firebase-schedule-EmailPendingAccounts-us-central1?pubsub_trigger=true
2002:a05:6680:2903:b0:8c:9ada:dd8 - "POST https://STUFF.appspot.com/_ah/push-handlers/pubsub/projects/passfolio-frontend-production/topics/firebase-schedule-EmailPendingAccounts-us-central1?pubsub_trigger=true" 500 undefined "CloudPubSub-Google"
Expand all | Collapse all{
 httpRequest: {…}  
 insertId: "INSERT_ID"  
 logName: "projects/passfolio-frontend-production/logs/cloudfunctions.googleapis.com%2Frequests"  
 receiveTimestamp: "2021-08-30T12:00:12.326791344Z"  
 resource: {…}  
 severity: "ERROR"  
 textPayload: "The request was aborted because there was no available instance."  
 timestamp: "2021-08-30T12:00:12.324916Z"  
 trace: "projects/passfolio-frontend-production/traces/TRACE_ID"  
}

2. Example Pub/Sub topic listener now generates 429 errors "The request was aborted because there was no available instance."

This didn't used to happen. What changed? Things seem to run without a problem though.

export const CopyUrlToCloudStorageTrigger = functions
  .runWith({
    timeoutSeconds: 540,
    memory: '2GB',
    maxInstances: 10,
    vpcConnector: 'fes-redis',
    vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY'
  })
  .pubsub.topic(consts.pubSub.TOPIC_COPY_URL_TO_CLOUD_STORAGE)
  .onPublish(async (message: functions.pubsub.Message, context: functions.EventContext) => {

2002:a05:6611:3689:b0:24c:ee5d:b917 - "POST https://STUFF_ID.appspot.com/_ah/push-handlers/pubsub/projects/passfolio-frontend-production/topics/TOPIC_COPY_URL_TO_CLOUD_STORAGE?pubsub_trigger=true" 429 14 "CloudPubSub-Google"
Expand all | Collapse all{
 httpRequest: {…}  
 insertId: "INSERT_ID"  
 logName: "projects/passfolio-frontend-production/logs/cloudfunctions.googleapis.com%2Frequests"  
 receiveTimestamp: "2021-08-31T13:32:11.921520381Z"  
 resource: {…}  
 severity: "WARNING"  
 textPayload: "The request was aborted because there was no available instance."  
 timestamp: "2021-08-31T13:32:11.628585Z"  
 trace: "projects/passfolio-frontend-production/traces/TRACE_ID"  
}

**Comment by dgobaud** [comment] 2021-08-31 15:18
3. around 2021-08-30 14:30:36.351 PDT we saw cloud functions that are not HTTP handlers get spammed with _ah/healthcheck

example below this doesn't make any sense for a firestore onWrite handler right?

export const UserAddsOrRemovesFavoriteAssetTrigger = functions
  .runWith({
    timeoutSeconds: 540,
    memory: '2GB',
    maxInstances: MAX_INSTANCES_DEFAULT,
    vpcConnector: 'fes-redis',
    vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY'
  })
  .firestore.document(
    `/${jsl.firebase.firestore.consts.COLLECTION_USERS}/{userId}/${jsl.firebase.firestore.consts.COLLECTION_USERS_APP_DATA}/${jsl.firebase.firestore.consts.DOCUMENT_USERS_USER_ASSETS}`
  )
  .onWrite((_change: functions.Change<FirebaseFirestore.DocumentSnapshot>, context: functions.EventContext) => {

{
 httpRequest: {
  latency: "0s"   
  protocol: "HTTP/1.1"   
  remoteIp: "2002:a05:6600:e58:b0:129:741:46f1"   
  requestMethod: "GET"   
  requestSize: "245"   
  requestUrl: "https://STUFF.appspot.com/_ah/healthcheck"   
  responseSize: "14"   
  status: 429   
 }
 insertId: "INSERT_ID"  
 logName: "projects/passfolio-frontend-development/logs/cloudfunctions.googleapis.com%2Frequests"  
 receiveTimestamp: "2021-08-30T21:30:36.359033218Z"  
 resource: {
  labels: {
   function_name: "UserAddsOrRemovesFavoriteAssetTrigger"    
   project_id: "passfolio-frontend-development"    
   region: "us-central1"    
  }
  type: "cloud_function"   
 }
 severity: "WARNING"  
 textPayload: "The request was aborted because there was no available instance."  
 timestamp: "2021-08-30T21:30:36.351787Z"  
 trace: "projects/passfolio-frontend-development/traces/TRACE_ID"  
}

**Comment by taeold** [comment] 2021-08-31 18:42
This seems like a dupe of https://github.com/firebase/firebase-functions/issues/962#issuecomment-908751821.

I think GCF team is working through cleaning up the logging to make this less surprising. In your case, contacting support is the right step - I (as a Firebase Functions engineer) don't have access to the GCF logs on your project. Please follow along in the public tracker or on your support case. If there is anything we can help with, feel free to reopen this issue.

**Closed by taeold** 2021-08-31 18:42 UTC
Labels: needs-triage
