### ISSUE TITLE
Can't Import ImageMagick gm library with ES6

### ISSUE THREAD

**Issue by Flucadetena** [firebase/firebase-functions#806] opened 2020-10-29 18:05 UTC
### Related issues

Haven't seen any.

### Version info

node: v12.16.3
"firebase-admin": "^9.3.0",
"firebase-functions": "^3.11.0",
"gm": "^1.23.1"
Firebase-tools: 8.14.1

### Test case

```
import * as functions from "firebase-functions";
import { createWriteStream } from "fs";
import axios from "axios";
import gm from "gm";
gm.subClass({imageMagick: true});

export const testTreatImage = functions.https.onRequest(async (req, res) => {
	try {
		const url = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/best-skincare-products-glowing-skin-1561735403.png";
		const originalPath = "/tmp/original.jpg";
		await downloadImage(url, originalPath);
		await treatImg(originalPath);

		res.status(200).send({ message: "OK" });
	} catch (err) {
		console.error(`Error saving the image: `, err.toString());
		res.status(400).send({ message: "ERROR" });
	}
});

async function downloadImage(url: string, originalPath: string) {
	try {
		const decodeUrl = decodeURIComponent(url);
		const res = await axios.get(decodeUrl, { responseType: "stream" });

		res.data.pipe(createWriteStream(originalPath));

		return new Promise<string>((resolve, reject) => {
			res.data.on("end", () => {
				resolve(originalPath);
			});

			res.data.on("error", () => {
				console.log("Err");
				reject();
			});
		});
	} catch (err) {
		console.error("Error downloading the img: ", err.toString());
		throw new Error();
	}
}

async function treatImg(originalPath: string) {
	try {
		const saveImg = (path: string, event: gm.State) => new Promise((resolve) => event.write(path, resolve));

		await saveImg(
			originalPath,
			gm(originalPath).fill("rgb(247,247,247)").fuzz(5, true).opaque("rgb(255,255,255)").quality(50).resize(1000, undefined, "^").strip(),
		);

		return null;
	} catch (err) {
		console.error("Error treating the img and resizing: ", err.toString());
		throw new Error();
	}
}
```
### Steps to reproduce

Execute de code.

###  Expected behavior

To process the image, as it does when importing with `const gm = require('gm').subClass({imageMagick: true});` but you don't get types in this case.

### Actual behavior
Error treating the img and resizing: Error: Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-quality" "50" "/tmp/original.jpg" "-fill" "rgb(247,247,247)" "-fuzz" "5%" "-opaque" "rgb(255,255,255)" "-resize" "1000x^" "+profile" "\"*\"" "+comment" "/tmp/1000.jpg" this most likely means the gm/convert binaries can't be found

### Were you able to successfully deploy your functions?

Yes, no problem!

**Comment by taeold** [comment] 2021-04-23 19:43
Long overdue answer, but I think this [stackoverflow](https://stackoverflow.com/questions/35132369/how-to-import-node-module-passing-subclass-argument-in-es6) answer could help us:

```
import gm from "gm";
const im = gm.subClass({ imageMagick: true });
```

**Comment by taeold** [comment] 2021-04-28 18:45
It looks like the original bug report that prompted creation of this one is marked closed:

https://github.com/firebase/firebase-functions/issues/337

I don't think we ever got to the bottom of the issue b/c the issue was irreproducible (which was kind of the point of the bug, but it became even more irreproducible and the issue was closed).

Closing this one b/c pasted code contains error w/ in how gm was being imported in es6. Any other user using the ES6 module import should check out the compiled code to see they are correctly applying `subClass` to their imported module.

**Closed by taeold** 2021-04-28 18:45 UTC
Labels: api: http
