### ISSUE TITLE
Hosting rewrite to function doesn't work

### ISSUE THREAD

**Issue by Bartinger** [firebase/firebase-functions#488] opened 2019-06-25 14:51 UTC
### [REQUIRED] Version info

**node:** v8.15.0
**firebase-functions:** 3.0.1
**firebase-tools:** 7.0.1
**firebase-admin:** 8.2.0

### [REQUIRED] Test case

```json
{
  "hosting": {
    "public": "dist/empty",
    "rewrites": [
      {
        "source": "/foo",
        "destination": "/test.html"
      },
      {
        "source": "/bar",
        "function": "api"
      },
      {
        "source": "**",
        "function": "api"
      }
    ]
  },
  "functions": {
    "source": ".",
    "ignore": [
      "node_modules",
      "scripts",
      "src",
      ".env_sample",
      ".env",
      ".gitignore",
      "tsconfig.json"
    ]
  }
}
```
https://github.com/freshfox/codeship-telegram-bot

### [REQUIRED] Steps to reproduce

There's a single html file deployed called `test.html`
https://build-notifier-bot.web.app/test.html

[/foo](https://build-notifier-bot.web.app/foo) correctly rewrites to `test.html`. 

### [REQUIRED] Expected behavior

I added a middleware to see if the request reaches the express application
```typescript
app.use((req, res) => {
	console.log(req);
	res.send('works');
});
```

https://github.com/freshfox/codeship-telegram-bot/blob/master/src/app/server.ts#L8

[/bar](https://build-notifier-bot.web.app/bar) and [**](https://build-notifier-bot.web.app/asd) should redirect to the [api](https://europe-west1-build-notifier-bot.cloudfunctions.net/api) function.

### [REQUIRED] Actual behavior

Those rewrites lead to a 404 page

### Were you able to successfully deploy your functions?

Successfully deployed at https://europe-west1-build-notifier-bot.cloudfunctions.net/api

**Comment by mbleigh** [comment] 2019-06-25 14:59
Firebase Hosting can currently only rewrite to functions in the us-central1
region.

**Comment by joehan** [comment] 2019-06-25 21:44
Closing this since it is intended behavior.

**Closed by joehan** 2019-06-25 21:44 UTC
Labels: needs-triage
