### ISSUE TITLE
Incorrect FireStore Trigger Function is Executed

### ISSUE THREAD

**Issue by vdiaz1130** [firebase/firebase-functions#1053] opened 2022-03-03 02:14 UTC
### Related issues
No related issues that I know of.

### [REQUIRED] Version info
I installed the latest firebase-tools globally
```
"dependencies": {
  "firebase-admin": "^9.8.0",
  "firebase-functions": "^3.14.1"
},
"devDependencies": {
  "@typescript-eslint/eslint-plugin": "^3.9.1",
  "@typescript-eslint/parser": "^3.8.0",
  "eslint": "^7.6.0",
  "eslint-config-google": "^0.14.0",
  "eslint-plugin-import": "^2.22.0",
  "firebase-functions-test": "^0.2.0",
  "typescript": "^3.8.0"
}
```

**node:**
node v14.17.5
npm v7.23.0

**firebase-functions:**
^3.14.1

**firebase-tools:**
10.2.2

**firebase-admin:**
^9.8.0

### [REQUIRED] Test case
Here's a minimal repo:
https://github.com/vdiaz1130/test-fb-functions

### To reproduce issue:

1. Clone project
2. cd into functions directory
3. Review functions/src/index.ts
4. npm install packages
5. Replace all refs of "MY_FB_PROJECT" with your project ID
6. npm run serve
7. Visit emulators (http://localhost:4002/firestore/data)
8. Create a "users" collection (note log in terminal) Says Beginning execution of "addUserToIndex"
9. Create a "brands" collection (note log in terminal) Says Beginning execution of "addUserToIndex" should be addBrandToIndex
10. Edit users document (note log in terminal) Beginning execution of "addUserToIndex" should be updateUserIndex
11. Edit brands document (note log in terminal) Beginning execution of "addUserToIndex" should be updateBrandIndex
12. Delete users document (note log in terminal) Errors - should execute deleteUserFromIndex but it's failing because addUserToIndex is being executed
13. Delete brands document (note log in terminal) Errors - should execute deleteBrandFromIndex but it's failing because addUserToIndex is being executed

### [REQUIRED] Expected behavior
The correct trigger function should be executed when interacting with FireStore collections (e.g. onCreate, onUpdate, onDelete for the collection being interacted with)

### [REQUIRED] Actual behavior
Only the first onCreate trigger is being executed regardless of the interaction (create, update, delete) or collection being manipulated (i.e. manipulating brands collection is triggereing onCreate for users collection)

### Were you able to successfully deploy your functions?
N/A

**Comment by vdiaz1130** [comment] 2022-03-03 02:53
Removing `--inspect-functions` from `"serve": "npm run build && firebase emulators:start --inspect-functions"` seems to fix the problem [🤦](https://emojipedia.org/person-facepalming/) 

I'll test in my original project and see if this indeed fixes it...

**Comment by taeold** [comment] 2022-03-03 02:55
@vdiaz1130 This looks like a dupe of https://github.com/firebase/firebase-tools/issues/4189 - we recently shipped a bug where `--inspect-functions` behaves just as you described. It should be fixed w/ the latest version of the Firebase CLI.

**Closed by taeold** 2022-03-03 02:55 UTC
Labels: needs-triage

**Comment by vdiaz1130** [comment] 2022-03-03 03:07
Got it. It's working again. Thanks!
