### ISSUE TITLE
Cannot read property 'name' of undefined at Firestore.snapshot_

### ISSUE THREAD

**Issue by shiraishimai** [firebase/firebase-functions#777] opened 2020-09-11 13:34 UTC
### Related issues
#528
#457
#447

All the related issues are closed out of no solid fix.

### [REQUIRED] Version info

**node: 10**

**firebase-functions: 3.8.0, 3.6.1**

**firebase-tools: 8.6.0, 8.2.0**

**firebase-admin: 9.0.0, 8.10.0**

### [REQUIRED] Test case

Hook on Firestore
```
functions.firestore
.document(id)
.onWrite()
```

### [REQUIRED] Steps to reproduce

Freshly built cloud functions will not reproduce.
Wait for the cloud function to be fully cooled down by not triggering the function for a month.
Then trigger the function.

### [REQUIRED] Expected behavior

Expected the cold bootup cloud functions to behave exactly the same as hot bootup.

### [REQUIRED] Actual behavior

```
watchSubscriptionChange
    TypeError: Cannot read property 'name' of undefined at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:569:128)
     at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:138:30)
     at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:142:49)
     at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:130:34)
     at Promise.resolve.then (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:198:28)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Were you able to successfully deploy your functions?

Yes, no error message for every deploy.

### Note

The reason why I had 2 versions reported above, is because when I first built the function and trigger it had no errors,
then after a month I encountered the error, I thought my code has been obsoleted, then I remove the cloud function and proceed with the upgrade from 
{
firebase-functions: 3.6.1 -> 3.8.0,
firebase-tools: 8.2.0 -> 8.6.0,
firebase-admin: 8.10.0 -> 9.0.0
}
, a freshly built cloud functions have no errors, but then I encounter the error again after a month, then I downgrade the dependencies back to previous versions, again, a freshly built cloud functions have no errors, then after a week, now the error appears again. So I believe this is related to cold bootup and hot bootup issue.

Now I am picking the approach of #447 and praying for the flag would work, but this issue is annoying because I cannot stop the failure retry inside the trigger function of `functions.firestore.document(id).onWrite()`, the error happens before I can check with the context timestamp in order to drop the failure event.

**Comment by huangjeff5** [comment] 2020-09-17 21:07
Hello,
I looked into your issue. Digging into the Firebase Functions code, it looks like the root cause is that the event is not passed in correctly to the Firestore onCreate handler. This issue will need to be escalated to the Firebase Data Plane team.

To dig into the issue further, we will need some additional info such as the Project ID, so that someone can investigate the specific issue. Please fill out the form [here](https://firebase.google.com/support/troubleshooter/contact), and someone will be in touch!

**Comment by shiraishimai** [comment] 2020-09-18 07:26
@huangjeff5 
Thank you for looking into this, an issue has been raised to firebase support.

**Comment by huangjeff5** [comment] 2020-09-21 22:43
Sounds good. Closing this issue out for now since it's outside of the domain of this repo.

**Comment by ErikSom** [comment] 2020-10-01 07:33
I'm experiencing a similar issue:
`TypeError: Cannot read property 'name' of undefined
    at RefBuilder.changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/database.js:117:85)
    at cloudFunctionNewSignature (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:104:28)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
    at Promise.resolve.then (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28)
    at process._tickCallback (internal/process/next_tick.js:68:7) `

Is this related?

**Comment by Marcin951** [comment] 2020-10-19 14:39
I guess I met similar issue `Unhandled error TypeError: Cannot read property 'fullName' of undefined
    at exports.createUsersChat.functions.https.onCall (/workspace/index.js:207:39)` It's appers completly random, sometimes this works sometimes I got an error

**Comment by KailashMaden** [comment] 2020-12-05 10:47
`Unhandled Rejection (TypeError): Cannot read property 'name' of null
Observer.complete
D:/React/mancity/node_modules/react-firebase-file-uploader/lib/index.js:150
(anonymous function)
D:/React/src/implementation/async.ts:27
  24 | export function async(f: Function): Function {
  25 |   return (...argsToForward: unknown[]) => {
  26 |     // eslint-disable-next-line @typescript-eslint/no-floating-promises
> 27 |     Promise.resolve().then(() => f(...argsToForward));
  28 |   };
  29 | }`

**Comment by jasony4** [comment] 2020-12-12 19:25
Is this a similar issue? 

![Screenshot 2020-12-12 at 19 23 42](https://user-images.githubusercontent.com/61871416/101993090-b8a9a100-3caf-11eb-991e-8eb4e97ead0d.png)

**Comment by KailashMaden** [comment] 2020-12-13 16:18
yeah that was the same, i made it, just it was the typo error: wrong
collection name in code, check your collection name of firebase and also
see the structure of collection and correct it bro!

**Comment by vitalikda** [comment] 2021-05-09 07:59
Same issue here with Firebase Emulator. If it helps someone, here is a solution.

SOLUTION: Restart emulator! 😅

**Comment by taeold** [comment] 2021-08-30 18:28
Hi @shiraishimai. Are you still having problem with this issue? Any luck from Firebase support team? Kindly give us a ping and we will take a new look at this.

Other issues doesn't seem related to the original report. Please open up a new issue if you are seeing a different stack trace.

**Closed** 2021-09-13 01:00 UTC
Labels: api: firestore, Needs: Author Feedback, no-recent-activity
