### ISSUE TITLE
[FR] Allow full cloud function config via FunctionBuilder API

### ISSUE THREAD

**Issue by joshdifabio** [firebase/firebase-functions#559] opened 2019-09-17 12:20 UTC
**Is your feature request related to a problem? Please describe.**
When deploying firebase functions to new projects, I have to manually edit the functions via the GCP web console in order to set timeouts, enable retries, etc., for different functions. It's easy to make a mistake when doing this and, after deploying functions for the first time, there is a period during which they are live with the wrong config (i.e. the wrong timeout or retry config) because I can't configure the functions in the GCP UI until the deployment is complete.

**Describe the solution you'd like**
I would like to be able to set function timeouts, enable retries (failurePolicy), etc., via the firebase-functions `FunctionBuilder` API, in the same way I can set the region.

**Describe alternatives you've considered**
I've looked at updating my functions via a bash script and the `gcloud` command line tool, but this really belongs with the rest of the non-environment-specific functions config (e.g. regions) in my source code.

Edit: It's actually possible to set function timeouts via `FunctionBuilder.runWith()`, so this issue only applies to retries (failurePolicy).

**Comment by samtstern** [comment] 2019-11-27 18:36
@joshdifabio sorry for the really delayed response here but the FR to implement retry policies is a duplicate of https://github.com/firebase/firebase-functions/issues/425

The good news is that #482 implements the solution for this and we do plan to release this once we can get the necessary changes in the Firebase CLI

**Closed by samtstern** 2019-11-27 18:36 UTC
Labels: needs-triage
