### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined at RefBuilder.changeConstructor

### ISSUE THREAD

**Issue by jpreynat** [firebase/firebase-functions#447] opened 2019-05-24 21:43 UTC
### Related issues

None really.

### [REQUIRED] Version info

**node:**
`v10.15.3`

**firebase-functions:**
`2.3.0`

**firebase-tools:**
`6.10.0`

**firebase-admin:**
`7.3.0`

### [REQUIRED] Test case

Deploy a database trigger on Node 10 runtime and make it run by updating the database.

### [REQUIRED] Steps to reproduce

Same as above.

### [REQUIRED] Expected behavior

I just tested upgrading our functions from Node 8 to Node 10. I expected the transition to go smoothly.

### [REQUIRED] Actual behavior

Everything is working fine locally with `firebase-tools@6.10.0` and `firebase-functions-test@0.16.0` (which works like a charm ATM, and is way faster than the previous emulator).
Deploying is working great too.
But the functions crash with the following logs:
```
Function execution took 8021 ms, finished with status: 'error'
```
```
TypeError: Cannot read property 'name' of undefined at RefBuilder.changeConstructor (/srv/functions/node_modules/firebase-functions/lib/providers/database.js:117:85)
  at cloudFunctionNewSignature (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:119:34)
  at cloudFunction (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:151:20)
  at Promise.resolve.then (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Were you able to successfully deploy your functions?

Some of our ~60 functions failed to deploy, but not more than the usual number, and not the ones that were tested.

**Comment by thechenky** [comment] 2019-05-29 21:54
Hi @jpreynat thanks for filing! This does look like an issue on our end - could you provide a quick sample of your function code? Which specific trigger are you using - `onUpdate`, `onWrite`, or `onCreate`?

**Comment by thechenky** [comment] 2019-05-29 22:53
Confirming I can reproduce this with database triggered function with Node 10 runtime. Looking into this now.

**Comment by thechenky** [comment] 2019-05-31 20:37
Figured out the issue. There is a fork in our logic for massaging the raw event that comes in on the wire. We are looking for `X_GOOGLE_NEW_FUNCTION_SIGNATURE` environment variable and are expecting it to be set to true, since Node 8 started setting that. This is how we figure out whether it’s a new Event or a Legacy Event. Node 10 events are not legacy, but because that env var is missing, we are treating the raw data as if it’s a Legacy Event.

Internal issue reference: 134076873

**Comment by julianrichie** [comment] 2019-06-05 17:25
any updates on this?

**Comment by thechenky** [comment] 2019-06-05 17:27
Hi @julianrichie this is still in progress and is the next highest priority to fix. Thanks for your patience!

**Comment by LoveMeWithoutAll** [comment] 2019-06-10 05:10
I encountered same issue on upgrading node from 6 to v10. Anyway, on node 8, it works.

**Comment by thechenky** [comment] 2019-06-11 22:39
This is in progress now and will be fixed in https://github.com/firebase/firebase-functions/pull/460. Thanks for everyone's patience!

**Closed** 2019-06-12 21:26 UTC
Labels: api: realtime-database, node-10, tracked internally, type: bug

**Comment by thechenky** [comment] 2019-06-13 00:56
This has been released in v3.0.1.

**Comment by jpreynat** [comment] 2019-06-13 09:14
Thanks @thechenky, I will test it quickly 👍

**Comment by jpreynat** [comment] 2019-06-13 10:07
And it works like a charm, thanks 🚀

**Comment by thechenky** [comment] 2019-06-14 08:09
Awesome, glad it's working @jpreynat! Thanks for testing it out :)

**Comment by katomihaivalergit** [comment] 2020-02-25 21:55
> I encountered same issue on upgrading node from 6 to v10. Anyway, on node 8, it works.

Thanks for the help. I had to rollback from vers. 10 to vers  8 and then it worked.
After the warning sent by google / firebase via email that I need to upgrade from 6, I did the upgrade to vers. 10 and noticed only after 1 month that some of my notification did not work. 👎
Did not check the logs...did not get any error on firebase deploy command.

So I hat to rollback to vers 8:
Set the version in the engines field in the package.json file that was created in your functions/ directory during initialization. For example, to use only version 8, edit this line in package.json:
  "engines": {"node": "10"} - not working. 
  "engines": {"node": "8"}
  
Hope this bug will be fixed in the vers 10 (release) not BETA.

**Comment by lunedam-git** [comment] 2020-05-24 19:56
It's now late May and I find that I still have to set process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = 'true'; in order for my functions to work in Node 10 (which is still it seems only in beta despite the mail bombing from Google about updating). Surely this should be resolved by now?

**Comment by liezl200** [comment] 2020-08-17 22:38
Setting `process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = 'true'; `in my index.js is not working. I also tried `process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = true;`
  I still get "TypeError: functions.storage.bucket(...).onFinalize is not a function"

**Comment by lunedam-git** [comment] 2020-08-18 12:16
Hey @liezl200 , I don't think your error has anything to do with the NEW_FUNCTION signature. Looks like it's a Typescript warning that there's something wrong with your code.

Try "functions.storage.object().onFinalize..." if you're listening for changes on the default bucket or "functions.storage.bucket('MYBUCKET').object().onFinalize..." if you're listening for changes on a bucket called 'MYBUCKET'.

See the docs at [https://firebase.google.com/docs/functions/gcp-storage-events](https://firebase.google.com/docs/functions/gcp-storage-events)

**Comment by cwchong** [comment] 2021-02-09 11:17
Has this been fixed? Encountering this post deploy to node 10

**Comment by ckuether** [comment] 2021-02-21 21:42
After running into this issue myself, I contacted Firebase support and was able to upgrade to Node 10 without breaking current functions.  

There could be an incompatibility with the firebase-functions module that you have in your project. As a first step, I need you to update to the latest version of the firebase-functions which is the v3.13.1 in your package.json. Then, delete your node_modules folder and execute npm install to reinstall all modules. 

Finally, I need you to update to the latest version of the Firebase CLI by running the command sudo npm install -g firebase-tools to get the latest updates and bug fixes. After all the steps mentioned before, test again your code, this time everything will be up to date and you should stop receiving errors.
