### ISSUE TITLE
Installation causes warning regarding firebase-admin

### ISSUE THREAD

**Issue by mbain** [firebase/firebase-functions#354] opened 2018-12-11 23:03 UTC
### Version info

**firebase-functions:**
2.1.0
**firebase-tools:**
6.1.2
**firebase-admin:**
6.3.0
### Test case

With firebase-admin 6.3.0 installed, when installing firebase-functions 2.1.0 via nom, it issues a warning stating that firebase-functions requires firebase-admin@~6.0.0, but that no version of firebase-admin is installed.

### Steps to reproduce

1) Install firebase-admin@6.3.0 via npm
2) Install firebase-functions@2.1.0 via npm
3) Read warning message

### Were you able to successfully deploy your functions?

Yes.

### Expected behavior

Successful installation via npm without warnings.

### Actual behavior

The following warning is issued by npm:
`npm WARN firebase-functions@2.1.0 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by thechenky** [comment] 2018-12-14 23:08
Hi @mbain! This is intended behavior as peer dependencies are not meant to be installed automatically by npm for compatibility issues. The version of admin that is required by this version of firebase-functions starts with ~, which [matches the most recent minor version](https://stackoverflow.com/a/22345808). It will complain if you have anything other than 6.0.x installed. You need to uninstall 6.3.0 and install 6.0.x by running `npm install firebase-admin@~6.0.0`.

**Comment by holyspidoo** [comment] 2018-12-17 11:58
The problem is that Firebase documentation found at [here](https://firebase.google.com/docs/functions/get-started) says to do this:
```
npm install firebase-functions@latest firebase-admin@latest --save
npm install -g firebase-tools
```

That will always cause the issue.

**Comment by thechenky** [comment] 2018-12-18 06:06
@holyspidoo good catch, thank you - we will update the docs.

**Comment by thechenky** [comment] 2018-12-19 22:57
I've dug into this a bit - we have had some issues with using `^` with `firebase-admin` before, mostly around when firebase-admin added new types in minor versions it would break our Typescript users. We are going to revisit this decision to see if we can return to `^`, and will update this issue when I have more info. In any case, we will update the docs accordingly.

**Comment by thechenky** [comment] 2018-12-19 23:00
Similar issue: #342

**Comment by thechenky** [comment] 2018-12-27 21:14
Hi all, a quick update and resolution to this:

For context: we previously used `^` for the firebase-admin dependency, but since switched to using `~` as interface changes in firebase-admin, which were released in minor version bumps, would break Typescript users in firebase-functions. The `~` limited firebase-admin to a specific minor revision, thus ensuring compatibility between the two.

After revisiting this discussion, we've come to a decision that we will keep the `~` versioning on the firebase-function SDK in order to not break Typescript users, but make sure to update firebase-functions to require the correct minor revision of firebase-admin after an admin minor version bump. This way the @latest of each SDK would always work together [as described in our docs](https://firebase.google.com/docs/functions/get-started#set-up-nodejs-and-the-firebase-cli). You should see these updates shortly.

Thanks for everyone's patience - I'm going to close this out now.

**Closed by thechenky** 2018-12-27 21:14 UTC
Labels: npm
