### ISSUE TITLE
[Kotlin/JS] Error occurred while parsing your function triggers. Please ensure that index.js only exports cloud functions.

### ISSUE THREAD

**Issue by chrisbln** [firebase/firebase-functions#664] opened 2020-04-21 06:47 UTC
### [REQUIRED] Version info

**node:** 8

**firebase-functions:** 3.6.0

**firebase-tools:** 8.1.1

**firebase-admin:** 8.10.0

### [REQUIRED] Test case

The problem occurs through the line ` $$importsForInline$$.index = _;`

Here is the full example of the index.js:

```
(function (_, Kotlin) {
  'use strict';
  var $$importsForInline$$ = _.$$importsForInline$$ || (_.$$importsForInline$$ = {});
  var PrimitiveClasses$stringClass = Kotlin.kotlin.reflect.js.internal.PrimitiveClasses.stringClass;
  var defineInlineFunction = Kotlin.defineInlineFunction;
  var wrapFunction = Kotlin.wrapFunction;
  function main$lambda(req, res) {
    PrimitiveClasses$stringClass;
    console.log("Starting first function 'hello'");
    return res.status(200).send('Hello World!');
  }
  function main(args) {
    var functions = require('firebase-functions');
    var admin = require('firebase-admin');
    admin.initializeApp(functions.config().firebase);
    exports.hello = functions.https.onRequest(main$lambda);
  }
  var firstKotlinFunction = defineInlineFunction('index.firstKotlinFunction_30y1fr$', wrapFunction(function () {
    var getKClass = Kotlin.getKClass;
    return function (T_0, isT) {
      return getKClass(T_0);
    };
  }));
  $$importsForInline$$.index = _;
  _.main_kand9s$ = main;
  main([]);
  Kotlin.defineModule('index', _);
  return _;
}(module.exports, require('kotlin')));

//# sourceMappingURL=index.js.map
```

You can find the full project on https://github.com/chrisbln/kotlin-firebase-functions-sample/blob/master/functions/src/main/index.js

### [REQUIRED] Steps to reproduce

1. I created a new Kotlin/JS project
2. The deployment and running of compiled Kotlin code to JavaScript works great with firebase functions
3. The exception is when adding the method `inline fun <reified T : Any>` in Kotlin
5. It generates JavaScript which is not working when deploying the firebase project, because of:`$$importsForInline$$.index = _;`
6. An example is here https://github.com/chrisbln/kotlin-firebase-functions-sample

### [REQUIRED] Expected behavior

Able to deploy the firebase functions. You can see the full example here:
https://github.com/chrisbln/kotlin-firebase-functions-sample

### [REQUIRED] Actual behavior

When I am trying to deploy the firebase functions it returns the given error message.

`firebase deploy --only functions`

### Were you able to successfully deploy your functions?

It displays the following error:
```
✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers. Please ensure that index.js only exports cloud functions.
```

**Comment by joehan** [comment] 2020-04-21 17:59
Hey @chrisbln, unfortunately, this looks like an issue with how you're cross compiling your Kotlin to JS. I'm having a bit of trouble grokking the compiled index.js code, but I suspect that this line is causing this problem:

```_.main_kand9s$ = main;```
Since `_` is `module.exports`, you are exporting your `main` function as `main_kand9s$`. Since `main` is not a cloud function, exporting it causes the error that you are seeing.

As to fixing this issue, unfortunately, I don't think anyone on the team here is familiar enough with Kotlin/JS to know what you need to change in your Kotlin to make this work.  You might have more luck asking this somewhere in the Kotlin community https://kotlinlang.org/community/

Going to close this for now since the code here is working as intended - feel free to reopen if you have more questions :)

**Closed by joehan** 2020-04-21 17:59 UTC
Labels: api: http

**Comment by chrisbln** [comment] 2020-04-21 18:37
Hi @joehan, thank you very much for the explanation. It helps me a little bit closer to getting my Kotlin Firebase Functions prototype up and running.

If I am removing this line then it works like a charm:
```
var $$importsForInline$$ = _.$$importsForInline$$ || (_.$$importsForInline$$ = {});
$$importsForInline$$.index = _;
```

Also if I reference the  importForInline to an empty function like:
``$$importsForInline$$.index =  {};``

I will contact the Kotlin team for a better understanding  :)
