### ISSUE TITLE
[Error] Missing or insufficient permission & initializeApp()

### ISSUE THREAD

**Issue by YBHwang** [firebase/firebase-functions#679] opened 2020-05-01 08:59 UTC
### Related issues

> Extend with Functions

### [REQUIRED] Version info

**node:** 8 & 10

**firebase-functions:** "^3.6.1"

**firebase-tools:** 8.2.0 (NPM)

**firebase-admin:** "^8.10.0"

### [REQUIRED] Test case

I already checked in both of node version, 8 and 10.

### [REQUIRED] Steps to reproduce

Set Firestore rules: Version 2

### [REQUIRED] Expected behavior

Suddenly I got this Error.

### [REQUIRED] Actual behavior

Top of the `index.js`
```node
const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp();

const db = admin.firestore();
```

------

#### Case 1
> `admin.auth().get...`
```console
Error fetching user data:  { Error: Credential implementation provided to initializeApp() via the "credential" property has insufficient permission to access the requested resource. See https://firebase.google.com/docs/admin/setup for details on how to authenticate this SDK with appropriate permissions.
    at FirebaseAuthError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAuthError (/srv/node_modules/firebase-admin/lib/utils/error.js:147:16)
    at Function.FirebaseAuthError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:186:16)
    at /srv/node_modules/firebase-admin/lib/auth/auth-api-request.js:1360:49
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  errorInfo: 
   { code: 'auth/insufficient-permission',
     message: 'Credential implementation provided to initializeApp() via the "credential" property has insufficient permission to access the requested resource. See https://firebase.google.com/docs/admin/setup for details on how to authenticate this SDK with appropriate permissions.' },
  codePrefix: 'auth' }
```

#### Case 2
> Using Firestore
```console
{ Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.
    at Object.callErrorFromStatus (/srv/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/srv/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:97:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  code: 7,
  details: 'Missing or insufficient permissions.',
  metadata: Metadata { internalRepr: Map {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient' }
```

### Were you able to successfully deploy your functions?

Success

**Comment by tinaliang** [comment] 2020-05-01 17:33
Hi YBHwang, without more detailed information it's hard to tell exactly what the cause of this could be.

You say you were able to successfully deploy your functions, so is this occurring only when you emulate the functions?

What are your Firestore rules currently?

Some documents that could be helpful potentially:
https://firebase.google.com/docs/admin/setup#add-sdk
https://firebase.google.com/docs/functions/local-emulator#set_up_admin_credentials_optional

**Comment by YBHwang** [comment] 2020-05-04 06:49
### Case 1

> Problem caused by the added external dependency.

The package relies on `request`, but has been deprecated, which ultimately seems to affect the entire function. So after uninstalling the package in question and deleting the associated function, we redeployed the whole, not a single function distribution.

Finally, I solved the admin credential problem with initializeApp()

### Case 2

> Problem caused by the IAM role.

Cloud Functions use **App Engine default service account**
→ `[PROJECT_ID].appspot.gserviceaccount.com`

I'm not sure why this suddenly happened, but I resolved by granting the role of the `Firebase Admin SDK admin service agent`.

**Comment by andresgottlieb** [comment] 2020-05-25 23:24
I was able to solve this following @YBHwang 's Case 2 instructions. I'm also intrigued about this suddenly happening, this problem emerged once I was deploying a mirror instance of a running and working app. That app doesn't have the `Firebase Admin SDK admin service agent`role assigned to `[PROJECT_ID].appspot.gserviceaccount.com`

**Comment by laurenzlong** [comment] 2020-05-28 17:46
Thanks for the updates! Closing since it sounds like this issue is resolved.

**Closed by laurenzlong** 2020-05-28 17:46 UTC
Labels: needs-triage

**Comment by mesqueeb** [comment] 2020-07-18 15:27
I have CASE 2 as well.

Somehow my cloud functions, even though I did:
```
admin.initializeApp()
```
were using the `myid@appspot.gserviceaccount.com` (App Engine default) Service Account instead of the Firebase Admin Service Account...

Here you can see that my Firebase Admin Service Role is never used:

<img width="961" alt="Screenshot 2020-07-19 00 18 22" src="https://user-images.githubusercontent.com/3253920/87855822-c6076d00-c955-11ea-8feb-b0017d1295c5.png">

## Attempted solution 1

I added the Firebase Admin SDK role to the `myid@appspot.gserviceaccount.com` Service Role, but I still get permission errors, even with this:

<img width="981" alt="Screenshot 2020-07-19 00 19 38" src="https://user-images.githubusercontent.com/3253920/87855840-ea634980-c955-11ea-9e1e-9a4441a53bcd.png">

## Solution attempt 2

I tried the thing with the `export GOOGLE_APPLICATION_CREDENTIALS` and the settings like so:
```
admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  databaseURL: 'https://colorfulcasting-22977.firebaseio.com',
})
```
but still uses the App Engine default Service Account....

**Comment by mesqueeb** [comment] 2020-07-18 15:36
### Working Solution:
I added these roles to the App Engine default service account:
- Firebase Admin SDK Administrator Service Agent
- Service Account Token Creator

Then it worked.

Is this dangerous though?

**Comment by laurenzlong** [comment] 2020-07-20 19:13
@mesqueeb By default, all functions run with the identity of the App Engine default service account. If you would like to change this behavior to use a different service account, you can do so by following these instructions: https://cloud.google.com/functions/docs/securing/function-identity#deploying_a_new_function_with_a_non-default_identity .

**Comment by manwithsteelnerves** [comment] 2021-01-02 03:49
> I added these roles to the App Engine default service account:
> 
> * Firebase Admin SDK Administrator Service Agent
> * Service Account Token Creator
> 
> Then it worked.

I started facing the same error when I tried duplicating a working project. I was trying to re-creating the whole project with gcloud cli as its easy for creating new environments from command line.

I checked if the working project (done totally with firebase-tools cli earlier) has the permission Firebase Admin SDK Administrator Service Agent for App Engine default service account. But it doesn't have too.

Surprising thing is new project is able to access firestore only after adding the above role to app engine default service account.

Can someone tell what could be the issue?

**Comment by benomatis** [comment] 2022-04-05 17:01
For those who struggled to add the permissions, here are the steps to take:
1. Go to IAM and admin
2. Select the Service accounts menu on the left hand side
3. Under 'Service accounts for project '[Project Name]' copy the Email of the account that has 'App Engine default service account' under its Name column (should be `[project_id]@appspot.gserviceaccount.com`).
4. Select the IAM menu from the left hand side
5. Click +ADD on the very top (next to the 'IAM' title)
6. In the field 'New principals' paste the service account email copied in point 3
7. Select the role 'Firebase Admin SDK Administrator Service Agent'
8. Click SAVE.

Credits go to @ybhwang @mesqueeb @manwithsteelnerves

**Comment by sandeep-bastola** [comment] 2024-01-23 14:44
Adding these two roles resolved my error :
   1.  Firebase Admin SDK Administrator Service Agent
    2. Service Account Token Creator

**Comment by lukemmtt** [comment] 2024-01-23 17:09
For anyone still coming across this 4 year old thread, just figured I'd share what worked for me.

I was experiencing this issue ("insufficient permission")when setting up my functions, despite having configured the App Engine default service account with plenty of permissions. Then I learned this: 

- Cloud Functions (**1st gen**) use the App Engine default service account
  - PROJECT_ID@appspot.gserviceaccount.com
- Cloud Functions (**2nd gen**) use the **default compute service account**:
  - PROJECT_NUMBER-compute@developer.gserviceaccount.com

More information here: https://stackoverflow.com/questions/56618350/which-service-account-is-used-when-running-firebase-cloud-functions
