### ISSUE TITLE
Esbuild compiled code is not working with Cloud Storage triggers V2

### ISSUE THREAD

**Issue by snorreks** [firebase/firebase-functions#1273] opened 2022-10-20 16:27 UTC
Object triggers for cloud functions v2 is not working with esbuild. It is working for onCall and onRequest v2 functions, and other normal functions.

### Related issues

https://github.com/firebase/firebase-tools/issues/4974#issue-1370709191

### [REQUIRED] Version info

**node:** v16.16.0

**firebase-functions:** 3.24.1

**firebase-tools:** 11.15.0

**firebase-admin:** 11.2.0

### [REQUIRED] Test case

https://github.com/snorreks/firebase-cloud-functions-v2-object-triggers-bug

### [REQUIRED] Steps to reproduce

See the readme in the repo.

### [REQUIRED] Expected behavior

Want to deploy storage v2 triggers.

### [REQUIRED] Actual behavior
I get this error:
```
Error: Error: storage event trigger is missing bucket filter: {
  "eventType": "google.cloud.storage.object.v1.finalized",
  "retry": false,
  "eventFilters": {
    "resource": "mailvideo-test.appspot.com"
  }
}
```

### Were you able to successfully deploy your functions?

No

**Comment by snorreks** [comment] 2022-10-22 11:33
Having 'firebase-functions' as [external](https://esbuild.github.io/api/#external) when building with esbuild. And installing firebase-functions in functions directory works. 
But it would be great if this step is not required for storage v2 functions. As it works without having firebase-functions as an external dependency for other functions.

**Comment by akauppi** [comment] 2022-10-23 12:48
@snorreks Having a minimal reproducible sample would likely make this easier (faster) to be fixed.

(gentle request; I'm not affected myself by this, just watching)

**Comment by inlined** [comment] 2022-10-31 18:27
This is the same root cause as #1277. I'm going to close this bug and add some explanations there.

**Closed by inlined** 2022-10-31 18:27 UTC
Labels: needs-triage
