### ISSUE TITLE
Unable to deploy functions with Typescript

### ISSUE THREAD

**Issue by mlejva** [firebase/firebase-functions#355] opened 2018-12-13 02:50 UTC
### Version info

**firebase-functions:**
2.1.0

**firebase-tools:**
6.1.2

**firebase-admin:**
6.4.0

### Test case

When using Typescript together with firebase functions I'm unable to deploy any code because of the following error:
```
Error: mod.hasOwnProperty is not a function
```

Typescript version: 3.2.2

### Steps to reproduce

functions/index.ts
```
import * as functions from 'firebase-functions'
import * as admin from 'firebase-admin';

admin.initializeApp(functions.config().firebase);
admin.firestore().settings({ timestampsInSnapshots: true });
const env = functions.config();
...
```

Run `$ firebase deploy --only functions`

Result
```
✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: mod.hasOwnProperty is not a function
```

### Were you able to successfully deploy your functions?

No. I got the following error message - `Error: mod.hasOwnProperty is not a function`

### Expected behavior

Functions should get deployed.

### Actual behavior

`Error: mod.hasOwnProperty is not a function`

**Comment by kevinajian** [comment] 2018-12-13 20:33
I was unable to reproduce the issue. Is it possible to share more of your code / debug info?

**Comment by mlejva** [comment] 2018-12-13 22:30
Turns out it might be an Algolia issue since it's happening only if I'm exporting following variable
```
export const client = algoliasearch(env.algolia.appid, env.algolia.apikey);
```

Currently my `functions/src/index.ts` file looks following:
```

import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import * as algoliasearch from 'algoliasearch';

admin.initializeApp(functions.config().firebase);
admin.firestore().settings({ timestampsInSnapshots: true });

// Initialize the Algolia Client
const env = functions.config();

export const client = algoliasearch(env.algolia.appid, env.algolia.apikey);
export const artistsIndex = client.initIndex('artists');
export const releasesIndex = client.initIndex('releases');
```

My `package.json`
```
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "cp './.runtimeconfig.json' './lib/.runtimeconfig.json' && tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "algoliasearch": "^3.31.0",
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.1.0"
  },
  "devDependencies": {
    "@types/algoliasearch": "^3.30.1",
    "tslint": "~5.8.0",
    "typescript": "~2.8.3"
  },
  "private": true
}
```

When running `npm run deploy` I get the following error
```
Error: mod.hasOwnProperty is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ deploy: `firebase deploy --only functions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by thechenky** [comment] 2019-01-03 21:09
@mlejva thanks for the update - do you have a predeploy hook configured to compile your Typescript? It would be in your `firebase.json` file and look something like this (if you don't have it, add it in and run `firebase deploy` again):
```
 {
   "functions": {
     "predeploy": "npm --prefix functions run build",
   }
 }
```
Let me know if that helps.

**Comment by joehan** [comment] 2019-01-09 19:11
@mlejva I took a look at the error message that you are getting, and I believe it is coming from  extractTriggers.js (https://github.com/firebase/firebase-tools/blob/master/src/extractTriggers.js) in firebase-tools. This code is run when you 'firebase deploy' in order to find the names of your functions from what you export in index.ts. 
firebase deploy expects that src/index.ts is only exporting functions created via firebase-functions (or custom functions written to the same spec). You shouldn't export other things in your index.ts file.
Hopefully this helps! I'm going to close this since its not an issue with our codebase, but I'm happy to clarify any other questions you may have.

**Closed by joehan** 2019-01-09 19:11 UTC
Labels: typescript

**Comment by matheo** [comment] 2019-10-06 23:16
I just found that some bundlers/optimizers can remove the `__proto__` functions of the Object and that will break `firebase-tools` logic. See #1687
