### ISSUE TITLE
Firebase serve not finding functions after updating firebase-functions to 4.0.1

### ISSUE THREAD

**Issue by MathiasGilson** [firebase/firebase-functions#1280] opened 2022-10-26 14:19 UTC
### Related issues

not sure

###  Version info

**node:** v18.11.0

```
 "dependencies": {
        "@sendgrid/mail": "^7.6.2",
        "axios": "^0.19.0",
        "bluebird": "^3.7.2",
        "body-parser": "^1.19.0",
        "clean-webpack-plugin": "^3.0.0",
        "copy-webpack-plugin": "^5.1.1",
        "dayjs": "^1.11.4",
        "express": "^4.17.1",
        "firebase": "^9.12.1",
        "firebase-admin": "^11.2.0",
        "firebase-functions": "^4.0.1",
        "telegraf": "^4.9.1",
        "twilio": "^3.82.2"
    },
    "devDependencies": {
        "config": "^3.0.1",
        "config-webpack": "^1.0.4",
        "ts-loader": "^6.0.2",
        "typescript": "^4.7.3",
        "webpack": "^4.33.0",
        "webpack-cli": "^3.3.10",
        "webpack-node-externals": "^1.7.2"
    },
```

ts-config.json
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "jsx": "react",
        "allowJs": false,
        "sourceMap": true,
        "noImplicitAny": false,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": false,
        "lib": ["es6", "dom"],
        "baseUrl": "./"
    },
    "exclude": ["node_modules", "dist"]
}

```

### [REQUIRED] Steps to reproduce

=> use `firebase init functions` to create a new project
=> compile with `yarn run build`
=> I had to copy paste `package.json` in the lib folder
=> serve function with firebase use --add test-project && firebase serve --only functions --port=9090

Firebase does not detect the functions

```
i  functions: Watching "/Users/User/Documents/Temp/test/functions/lib" for Cloud Functions...
✔  functions: Loaded functions definitions from source: .
```

### Expected behavior

Serving the cloud functions

### Actual behavior

[debug] [2022-10-26T13:58:46.809Z] Validating nodejs source
[debug] [2022-10-26T13:58:47.080Z] ˜:  {}
[debug] [2022-10-26T13:58:47.080Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^4.0.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  },
  "private": true
}
[debug] [2022-10-26T13:58:47.080Z] Building nodejs source
[debug] [2022-10-26T13:58:47.080Z] Analyzing nodejs backend spec
[debug] [2022-10-26T13:58:47.445Z] Could not parse firebase-functions version '' into semver. Falling back to parseTriggers.
[info] ✔  functions: Loaded functions definitions from source: . {"metadata":{"emulator":{"name":"functions"},"message":"Loaded functions definitions from source: ."}}

### Were you able to successfully deploy your functions?

Rolling back to "firebase-functions": "3.24.1" works

**Comment by MathiasGilson** [comment] 2022-10-26 14:20
Ok so updating firebase.json from

```
{
    "functions": {
        "source": "./lib"
    }
}
```

to 

```
{
    "functions": {
        "source": "."
    }
}
```

Worked, I'm not sure why

**Comment by gbourne1** [comment] 2022-10-27 11:59
Same issue - seems 4.0.1 breaks the source directory. I don't see anything in the change logs, so might be unintended.

**Comment by inlined** [comment] 2022-10-31 18:27
This is the same root cause as #1277. I'm going to close this bug and add some explanations there.

**Closed by inlined** 2022-10-31 18:27 UTC
Labels: needs-triage
