### ISSUE TITLE
originalUrl doesn't include the higher subpaths by firebase, like "/projectId/region"

### ISSUE THREAD

**Issue by cgarrovillo** [firebase/firebase-functions#854] opened 2021-01-28 19:23 UTC
### Related issues

Possibly: 
https://github.com/firebase/firebase-functions/issues/27  

### [REQUIRED] Version info

**node:** 12.20.1

**firebase-functions:** 3.11.0

**firebase-tools:** 9.2.2

**firebase-admin:** 9.2.0

### [REQUIRED] Test case

When functions are placed in a group, `req.originalUrl` can't see the other paths "above" the Express layer and therefore returns the wrong `originalUrl`

Endpoint:  `https:/localhost:5001/projectId/us-central1/sms/test`
originalUrl: `/test`
baseUrl: ` `
path: `/`
app.mountpath: `/`

This becomes a real problem when the request URL's are being used to accurately calculate hashes.

-----
My theory is that this is because of how Express uses `req.originalUrl`,  where the `baseUrl` and the `path` is combined by Express, however, Express itself doesn't know that Functions is putting these endpoints under a group, thus adding another subpath "above" express that has the group. (`/sms`)

This is backed even further when `req.app.mountpath` is called,  where the output is `/` (as Express only knows itself)

### [REQUIRED] Steps to reproduce

```ts
/* /index.ts */

require('dotenv').config() // Get development environment variables
import functions = require('firebase-functions')

import { Sms } from './sms/sms.ts'

exports.sms = functions.https.onRequest(Sms)
exports.yolo = functions.https.onRequest((req, res) => {
  console.log(req.originalUrl)
  console.log(req.baseUrl)
  console.log(req.path)
  res.send(req.originalUrl)
})
```

```ts
/* /sms/sms.ts */

import express = require('express')
const app = express()

app.get('/test', (req, res) => {
  console.log(`-----------`)
  console.log(`HOST: ${req.get('host')}`)                       // localhost:5001
  console.log(`ORGURL: ${req.originalUrl}`)                  // /test
  console.log(`BASEURL: ${req.baseUrl}`)                    // 
  console.log(`path: ${req.path}`)                                  // /test
  console.log(`mountpath: ${req.app.mountpath}`)    // /
  console.log(`-----------`)

  res.send('test')
})

export { app as Sms }
```

### [REQUIRED] Expected behavior

Express `originalUrl` should be able to recognize the paths inferred by Functions from the function "group" of `sms`

and **not** just the Express paths: `/test`

```
>  HOST: localhost:5001
>  ORGURL: /projectId/us-central1/sms/test
>  BASEURL: /projectId/us-central1/sms
>  path: /test
>  mountpath: /
```

### [REQUIRED] Actual behavior

```
>  HOST: localhost:5001
>  ORGURL: /test
>  BASEURL: 
>  path: /test
>  mountpath: /
```

### Were you able to successfully deploy your functions?

Yes we can successfully deploy. The problem can also be seen in production.

**Comment by samtstern** [comment] 2021-02-04 14:13
@cgarrovillo this is the intended behavior and changing this in production would be a very breaking change for a lot of people, so it will have to remain this way.  

We recently changed `firebase-tools` to match the behavior in production when emulating. If you're seeing any differences in these paths between the latest CLI release and production, please file an issue on [our CLI repo](https://github.com/firebase/firebase-tools). Otherwise I'm going to close this as working as intended, even though I understand it's not the behavior you want.

**Closed by samtstern** 2021-02-04 14:13 UTC
Labels: api: http

**Comment by theoephraim** [comment] 2022-06-24 22:11
Is there any way to programmatically get the app name and region? This could be needed for example when generating an OAuth callback url. Looks like there is an env var with `GCLOUD_PROJECT` but I don't see anything to get the region, at least from env vars.
