### ISSUE TITLE
Error when try to Log with the firebase function logger on removeCircular function

### ISSUE THREAD

**Issue by qmarquez-codecare** [firebase/firebase-functions#1083] opened 2022-04-21 14:28 UTC
### [REQUIRED] Version info

**node:** both 12 and 14

**firebase-functions:** 3.20.1 (in 3.15.7 this issue don't happen)

**firebase-tools:** 10.7.0

**firebase-admin:** 9.12.0

### [REQUIRED] Test case

I can reproduce this issue only in firebase onCreateUser action, running the require('firebase-functions').logger.write function. Internally the function runs **removeCircular** function, in v3.15.7 logs fine the object coming from the onCreateUser action in v3.20.1 throws this error:
![image](https://user-images.githubusercontent.com/89588755/164478921-40991410-0d0a-40ed-ba0c-6d3af95d9178.png)
![image](https://user-images.githubusercontent.com/89588755/164479195-f535e58e-e316-436a-bd3f-5e4df15c629f.png)

### [REQUIRED] Steps to reproduce
Log the object coming from onCreateUser action with the write function in firebase-function (it seems like the user provided by the action has a toJSON property that is not a function)

### [REQUIRED] Expected behavior
The user coming from onCreateUser action could be logged

### [REQUIRED] Actual behavior
The actions breaks when try to log the user received 

### Were you able to successfully deploy your functions?
Yes

**Comment by aaga** [comment] 2022-05-02 22:58
I have the same issue. I believe it is being caused by this line:
https://github.com/firebase/firebase-functions/blob/1aa1865dc64d3aeab849fe7aed916f429d1231d1/src/common/providers/identity.ts#L145

The `providerData` is an array of type UserInfo, but UserInfo does not have a `toJSON` method.

**Comment by aaga** [comment] 2022-06-08 02:12
I believe this issue was a disguised duplicate of #1102 (OP has "entry.toJSON is not a function" in their error log) and can therefore now be closed.

**Closed** 2022-06-15 22:52 UTC
Labels: needs-triage
