### ISSUE TITLE
Angular Universal ES6 modules complied with babel is not working in firebase SSR hosting.

### ISSUE THREAD

**Issue by ananthu-confianz** [firebase/firebase-functions#477] opened 2019-06-18 12:56 UTC
### [REQUIRED] Version info

**node:**
8.16.0

**firebase-functions:**
2.3.0

**firebase-tools:**
6.11.0

**firebase-admin:**
7.0.0

### [REQUIRED] Test case

Run firebase deploy in console.
My functions/package.json

{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.3.0",
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/platform-server": "5.2.9",
    "@angular/router": "5.2.9",
    "@ng-bootstrap/ng-bootstrap": "./compiled_modules/@ng-bootstrap/ng-bootstrap",
    "@nguniversal/express-engine": "5.0.0",
    "@nguniversal/module-map-ngfactory-loader": "5.0.0",
    "bootstrap": "4.2.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19",
    "ts-loader": "3.5.0",
    "utf-8-validate": "5.0.1",
    "ws": "6.0.0",
    "xmlhttprequest": "1.8.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}

My firebase.json

{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "ssr"
      }
    ]
  }
}

functions/src/index.js

// Load zone.js for the server.
require('zone.js/dist/zone-node');
const functions = require('firebase-functions');
const express = require('express');
const path = require('path')

// Import renderModuleFactory from @angular/platform-server.
const renderModuleFactory = require('@angular/platform-server').renderModuleFactory;

// Import the AOT compiled factory for your AppServerModule.
// This import will change with the hash of your built server bundle.
const AppServerModuleNgFactory = require('./dist-server/main.bundle').AppServerModuleNgFactory;

// Load the index.html file.
const index = require('fs').readFileSync(path.resolve(__dirname, './dist-server/index.html'), 'utf8');

let app = express();

app.get('/', function(req, res) {
  renderModuleFactory(AppServerModuleNgFactory, {document: index, url: '/'})
      .then(function(html) {
         res.send(html);
      }).catch( function(e) {
         console.log(e)
      });
});

exports.ssr = functions.https.onRequest(app);

### [REQUIRED] Steps to reproduce
Refer github link: https://github.com/ananthu-confianz/angular-universal-demo
1. npm install in project directory to produce compiled node modules in functions as compiled_modules

2. Init firebase and provide hosting directory as dist, and cloud functions. Do not overwrite index.js

3. Run ng build --prod --app 1 --output-hashing=false to generate server packages in functions/dist-server

4. Copy src/index.html to functions/dist-server

5. npm i to install dependencies in functions directory.

6. Run firebase deploy in console.

### [REQUIRED] Expected behavior
Modules compiled with babel is provided as custom dependency should work on firebase hosting.

### [REQUIRED] Actual behavior
The modal is not triggered and styles are not applied. In general none of the functionality of ng-bootstrap is available in the hosted project which was compiled with babel.

### Were you able to successfully deploy your functions?
Yes

**Comment by thechenky** [comment] 2019-06-18 17:38
Hi @ananthu-confianz have you tried running it locally using `firebase serve`? Does it also not work? I'd also try to make your function as simple as possible and add log lines to see where the error may be coming from.

**Comment by ananthu-confianz** [comment] 2019-06-22 03:37
@thechenky yes, I have tried that. But it doesn't seems to be working.

**Comment by thechenky** [comment] 2019-06-23 23:49
It's difficult to help if you don't provide more information like log lines and what error is being returned when doing local firebase serve. Please try with a simple function to see if the issue persists or results in different errors.

**Comment by ananthu-confianz** [comment] 2019-06-24 09:34
@thechenky I have set up a minimal interface https://hosting-test-69220.firebaseapp.com/ based on https://github.com/ananthu-confianz/angular-universal-demo. There is no error either on firebase deploy or in the browser console at the run-time. The modal box is not getting triggered in the universal build.

**Comment by thechenky** [comment] 2019-06-24 15:49
This is not a minimal interface as there are many libraries involved. Please add log lines to see where the function is not being triggered, otherwise it's difficult to help as I said earlier. This question may be best suited for the repo you're reproducing this from - I'd either ask there or post on StackOverflow to see if others have figured out how to resolve this. This repo is for functions SDK issues, which you should be able to reproduce with a super simple setup using minimal libraries.

**Comment by thechenky** [comment] 2019-06-24 19:15
Since this is an issue with standing up an Angular app, StackOverflow would be the more appropriate channel for this as I mentioned in my previous comment. Since this is not an issue with the functions SDK, closing this out.

**Closed by thechenky** 2019-06-24 19:15 UTC
Labels: Needs: Attention, api: http
