### ISSUE TITLE
How to set runtime options in gen2 (v2) background triggers?

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-functions#1433] opened 2023-07-06 17:24 UTC
### [REQUIRED] Version info

**node:** 16

**firebase-functions:** 4.4.1

**firebase-tools:** 12.4.2

**firebase-admin:** 11.9.0

### [REQUIRED] Test case

How do you set runtime options at the function level? Example runtime options:

* timeoutSeconds
* memory

I would have expected to be able to do this, but it fails:

```
onDocumentWritten({
  document: 'widgets/{widgetId}',
  timeoutSeconds: 180
}, event => {})
```

Related StackOverflow question: https://stackoverflow.com/q/76274289/188740

### [REQUIRED] Steps to reproduce

Create a background function using gen2.

### [REQUIRED] Expected behavior

Runtime options are configurable at the function level through code.

### [REQUIRED] Actual behavior

Runtime options are not configurable at the function level through code.

### Were you able to successfully deploy your functions?

No

**Comment by iurage** [comment] 2023-07-07 13:44
Yes same here for adding secrets to `onSchedule` v2 functions.

**Comment by dlewis2017** [comment] 2023-07-08 02:51
I used `setGlobalOptions` 

E.g.
```
const { setGlobalOptions } = require("firebase-functions/v2");

setGlobalOptions({timeoutSeconds: 120, timeZone: "American/NewYork", enforceAppCheck: false});
...
// functions here
```

**Comment by blidd-google** [comment] 2023-07-10 20:27
Hi there, I'm unable to reproduce the error that you've described — could you provide a simple reproducible example i could use to see what you're seeing?

**Comment by johnnyoshika** [comment] 2023-07-19 15:35
Bump - anyone from Google/Firebase care to comment?

**Comment by inlined** [comment] 2023-07-27 20:49
As per above, we're waiting for help reproducing the problem. The following code compiles for me in a clean project:

```
import {onDocumentWritten} from "firebase-functions/v2/firestore";
import {onSchedule} from "firebase-functions/v2/scheduler";
import { defineSecret } from "firebase-functions/params";
import * as logger from "firebase-functions/logger";

const apiKey = defineSecret("API_KEY");

export const docHandler = onDocumentWritten({
  document: "widgets/{widgetId}",
  timeoutSeconds: 180,
}, event => logger.info("Got event from doc", event.location));

export const cron = onSchedule({
  schedule: "every monday 9:00",
  secrets: [apiKey],
}, (event) => logger.info("Welcome to a brand new week!"));
```

Can the affected users verify that they're using the latest version of `firebase-tools` and `typescript`?

**Comment by johnnyoshika** [comment] 2023-07-31 19:03
I just tried it again and to my surprise, the type definitions are there. Strangely, it's now failing eslint because it's unable to resolve path to firebase-functions/v2, but I think that's a different problem. If others can confirm that this is resolved (or never an issue), I'll close this issue.

**Comment by coehne** [comment] 2023-08-01 09:52
After finding the [V2 API docs](https://firebase.google.com/docs/reference/functions/2nd-gen/node/firebase-functions.globaloptions.md#globaloptions_interface) it made more sense to me. However, typescript is not showing the options to me in VS Code. Maybe it would help to mention in the functions docs that these options are available on all functions types, not only on the https ones or point to the API Reference docs for more information.

**Comment by blidd-google** [comment] 2023-08-22 19:28
Hi all, the docs linked [here](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#set_timeout_and_memory_allocation) provide instructions on configuring runtime options, including timeouts. Closing this issue for now, given that setting runtime options in 2nd gen functions is working as expected.

**Closed by blidd-google** 2023-08-22 19:28 UTC
Labels: Needs: Attention

**Comment by davidoort** [comment] 2024-03-04 11:59
Hey @blidd-google when will this work for firestore trigger functions? e.g.
`export const onProductWritten = onDocumentWritten("products/{productId}", (event) => handleProductWritten(event));`

**Comment by johnnyoshika** [comment] 2024-03-06 15:40
> Hey @blidd-google when will this work for 2nd gen Firestore trigger functions? e.g. `export const onProductWritten = onDocumentWritten("products/{productId}", (event) => handleProductWritten(event));`
> 
> Currently the only configuration option is the document path and global options, but no resources or instances for individual trigger functions....

It works for me:

```
onDocumentWritten(
  {
    document:
      'widgets/{widgetId}',
    minInstances: 1,
    timeoutSeconds: 7 * 60,
    memory: '1GiB',
  }
```

**Comment by davidoort** [comment] 2024-03-07 12:33
You're right! @johnnyoshika thank you!

**Comment by maganap** [comment] 2024-11-04 17:21
> I just tried it again and to my surprise, the type definitions are there. Strangely, it's now failing eslint because it's unable to resolve path to firebase-functions/v2, but I think that's a different problem. If others can confirm that this is resolved (or never an issue), I'll close this issue.

@johnnyoshika Late to the party but, yes, I can confirm it does work with `firebase-functions@6.0.1", and that VS Code has no clue there's another override with `DocumentOptions` as first argument. Options are not suggested 🤷🏻‍♀️
