### ISSUE TITLE
The email address is already in use by another account.

### ISSUE THREAD

**Issue by louranthy** [firebase/firebase-functions#101] opened 2017-09-10 13:16 UTC
### Version info

**firebase-functions:**^0.6.2

**firebase-tools:**

**firebase-admin:** ~5.2.1

### Steps to reproduce

I have the following function:

```
exports.createClientAccount = functions.database
  .ref('/appusers/{userId}').onWrite( event => {
  var ref = event.data.ref;
return admin.auth().createUser({
  emailVerified: false,
  email: event.data.val().email,
  password: password,
  displayName: event.data.val().firstName + ' ' + event.data.val().lastName,
  disabled: false
}).then(function (userRecord) {
  ref.update({
    "uid": userRecord.uid
  });
  return sendWelcomePassword(event.data.val());
}).catch(error => {console.log("Error creating new user:", error);
});

```

I created a onWrite trigger from appusers table. It will create a firebase user and will send an email after.
The problem is that the function logs will first give this error:

> 
> Cannot read property 'email' of null
>     at exports.createClientAccount.functions.database.ref.onWrite.event (/user_code/index.js:33:28)
>     at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:54:20
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Then it will be retriggered, although it will add a new firebase user and will send the email, there is an error still on the logs. 

> 
> Error creating new user: { Error: The email address is already in use by another account.
>     at FirebaseAuthError.Error (native)
>     at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
>     at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:104:23)
>     at Function.FirebaseAuthError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:128:16)
>     at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:399:45
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
>   errorInfo: 
>    { code: 'auth/email-already-exists',
>      message: 'The email address is already in use by another account.' } }

How come it says that the email address is already in use when it is the first time it has been used/created?

**Comment by katowulf** [comment] 2017-09-11 18:39
Hi @louranthy this is a usage question related to the timing of your requests. Most likely, your initial database write doesn't contain the email address (The `null` complaint is about `event.data.val().email`, because `.val()` is `null` so email can't be fetched). 

It's likely that the event is being called multiple times, and eventually working out (after the email address exists) and that you just need to simplify and slowly add back complexity until you isolate the error.

Closing this since it's a usage issue (not a simple, demonstrable bug that contradicts our docs or expected behavior).

**Closed by katowulf** 2017-09-11 18:39 UTC

**Comment by bitlab-code** [comment] 2017-09-21 17:08
Hi @katowulf 
_I'm reopening this issue because the error is the same but different probably causes._
I get the same error, but with no other errors or warnings 

`"firebase-admin": "^5.2.1"`
`"firebase-functions": "^0.6.3"`

I'm trying to insert two user with same email address but with different phone number.
When configure sign-in methods I setup only phone number as authentication provider (Email/password disabled) and I allowed multiple accounts with the same email address.

the snipped code of the function (onWrite):
```javascript
    const auth = admin.auth();
    /* ... */
    if (!event.data.previous.exists()) {
      const userData = event.data.current.val();
      console.log(`A new user was created: ${uid}. Now syncing in Auth...`, userData);
      return auth.createUser({
        uid: uid,
        email: userData.email,
        phoneNumber: userData.phone,
        disabled: false
      }).then(userRecord => {
        console.log(`Done. Created new user in Auth: ${uid}`, userRecord);
        return Promise.resolve(uid);
      }).catch(error => {
        console.error(`Error Creating new user in Auth: ${uid}`, error);
        sendEmail.logEmail(/* ... */);
        return Promise.reject(`${error}`);
      });
    } 
```
the log
```
Error Creating new user in Auth: -Ku_GnJvedvEbtfgn0xP { Error: The email address is already in use by another account.
    at FirebaseAuthError.Error (native)
    at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:104:23)
    at Function.FirebaseAuthError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:128:16)
    at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:399:45
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  errorInfo: 
   { code: 'auth/email-already-exists',
     message: 'The email address is already in use by another account.' } }
```
