### ISSUE TITLE
Log level can't be filtered after switch to node 10

### ISSUE THREAD

**Issue by xuaninbox** [firebase/firebase-functions#483] opened 2019-06-24 00:21 UTC
### Related issues

N/A

### [REQUIRED] Version info

**node:**

10

**firebase-functions:**

3.0.1

**firebase-tools:**

7.0.1

**firebase-admin:**

8.2.0

### [REQUIRED] Steps to reproduce

I have **console.info('xxx');** in my function, and log level can't be filtered on the console after switch to node 10, switch back to node 8 works fine.

**Comment by thechenky** [comment] 2019-06-24 19:13
@xuaninbox please fill out all the required fields of the template to provide more info on what filtering specifically, what it should look like, and screenshots would also be helpful.

**Comment by xuaninbox** [comment] 2019-07-03 19:53
By looking at the log for a console.info()

node 8

`{
 insertId:  "000000-"   
 labels: {
  execution_id:  "abc"    
 }
 logName:  "projects/projectId/logs/cloudfunctions.googleapis.com%2Fcloud-functions"   
 receiveTimestamp:  "2019-07-03T19:29:20.718026023Z"   
 resource: {
  labels: {
   function_name:  "f_sso_verify"     
   project_id:  "projectId"     
   region:  "us-central1"     
  }
  type:  "cloud_function"    
 }
 severity:  "INFO"   
 textPayload:  "buildLoginString done, redirect to url"   
 timestamp:  "2019-07-03T19:29:15.239Z"   
 trace:  "projects/projectId/traces/"   
}`

node 10

`{
 insertId:  "000000-"   
 labels: {
  execution_id:  "abc"    
 }
 logName:  "projects/projectId/logs/cloudfunctions.googleapis.com%2Fcloud-functions"   
 receiveTimestamp:  "2019-07-03T19:36:04.400314931Z"   
 resource: {
  labels: {
   function_name:  "f_sso_verify"     
   project_id:  "projectId"     
   region:  "us-central1"     
  }
  type:  "cloud_function"    
 }
 textPayload:  "buildLoginString done, redirect to url"   
 timestamp:  "2019-07-03T19:35:59.136Z"   
 trace:  "projects/projectId/traces/"   
}`

the **severity** key is gone, which caused the log level can't be filtered.

**Comment by thechenky** [comment] 2019-07-03 23:51
@xuaninbox please provide a quick code sample of your function so that I can try to reproduce on my end.

**Comment by thechenky** [comment] 2019-07-03 23:51
You will need to fill out all the REQUIRED sections in the issue template. Please do so.

**Comment by kevinajian** [comment] 2019-07-08 22:23
@xuaninbox Can you try checking the Cloud Console and see if the filtering works there?

**Comment by xuaninbox** [comment] 2019-07-12 07:34
firebase before and after
<img width="736" alt="1" src="https://user-images.githubusercontent.com/5108256/61110696-ad0fd600-a43c-11e9-8913-ec73864bad97.png">
Cloud Console
<img width="733" alt="2" src="https://user-images.githubusercontent.com/5108256/61110698-ae410300-a43c-11e9-8642-80b6a7fdd4b6.png">

No the filter does not work there.

**Comment by kevinajian** [comment] 2019-07-12 23:35
Since this seems like a logging issue which is outside of the scope of this sdk, can you file an issue with Google Cloud Functions (https://cloud.google.com/functions/docs/getting-support)?
I'll close this issue since we cannot resolve it here, but let us know if you run into any other problems.

**Closed by kevinajian** 2019-07-12 23:35 UTC
Labels: Needs: Attention

**Comment by tfang17** [comment] 2020-05-26 15:08
@xuaninbox Seeing the same issue. Were you able to resolve?
