### ISSUE TITLE
v2 Firestore Triggers Type definitions define .data property on FirestoreEvents as possibly undefined

### ISSUE THREAD

**Issue by wneild** [firebase/firebase-functions#1464] opened 2023-09-27 15:41 UTC
### [REQUIRED] Version info

**node:** 16.20.0

**firebase-functions:** 4.4.1

**firebase-tools:** 12.3.0

**firebase-admin:** 11.10.1

### [REQUIRED] Test case

```
export const exampleHandler = onDocumentCreated('example/{docId}', async (event) => {
	const docId = event.data?.id; // event data is possibly undefined
	info(docId);
});
````

### [REQUIRED] Steps to reproduce

1. Write the above code in a Node with Typescript configured environment
2. Observe the need to handle possibly undefined event data

### [REQUIRED] Expected behavior

I expect every Firestore event to, at minimum, have data on what occurred and never be undefined.

### [REQUIRED] Actual behavior

I am required to handle the possibility of undefined data on all Firestore events as per the following type defs:
```
export declare function onDocumentWritten<Document extends string>(document: Document, handler: (event: FirestoreEvent<Change<DocumentSnapshot> | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<Change<DocumentSnapshot> | undefined, ParamsOf<Document>>>;

export declare function onDocumentWritten<Document extends string>(opts: DocumentOptions<Document>, handler: (event: FirestoreEvent<Change<DocumentSnapshot> | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<Change<DocumentSnapshot> | undefined, ParamsOf<Document>>>;

export declare function onDocumentCreated<Document extends string>(document: Document, handler: (event: FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>>;

export declare function onDocumentCreated<Document extends string>(opts: DocumentOptions<Document>, handler: (event: FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>>;

export declare function onDocumentUpdated<Document extends string>(document: Document, handler: (event: FirestoreEvent<Change<QueryDocumentSnapshot> | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<Change<QueryDocumentSnapshot> | undefined, ParamsOf<Document>>>;

export declare function onDocumentUpdated<Document extends string>(opts: DocumentOptions<Document>, handler: (event: FirestoreEvent<Change<QueryDocumentSnapshot> | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<Change<QueryDocumentSnapshot> | undefined, ParamsOf<Document>>>;

export declare function onDocumentDeleted<Document extends string>(document: Document, handler: (event: FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>>;

export declare function onDocumentDeleted<Document extends string>(opts: DocumentOptions<Document>, handler: (event: FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>) => any | Promise<any>): CloudFunction<FirestoreEvent<QueryDocumentSnapshot | undefined, ParamsOf<Document>>>;
```

### Were you able to successfully deploy your functions?

Yes

**Comment by blidd-google** [comment] 2023-10-13 15:07
Hi @wneild, the union type is `FirestoreEvent<Change<DocumentSnapshot> | undefined, ...>`, _not_ `FirestoreEvent<...> | undefined`, meaning the `data` property of the event object may be undefined but not the event object itself. Therefore you shouldn't need to handle cases where the event parameter may be undefined.

**Comment by johnnyoshika** [comment] 2023-12-27 16:13
I'm also interested in this? In what scenario would event.data be undefined?

Background: event for onDocumentWritten is typed as:

```typescript
FirestoreEvent<Change<DocumentSnapshot> | undefined, ParamsOf<Document>>
```

**Comment by exaby73** [comment] 2024-01-05 10:57
There may be some documentation missing here. I'll label it as such

**Comment by taeold** [comment] 2024-07-18 16:45
Hey @johnnyoshika @wneild - thanks for the question!

After chatting with the team, I re-learned that the `.data` property may be empty if the snapshot for Firestore document being sent over the wire exceeds 10MB. This is very unlikely to happen, and when it happens you'll see a log in your GCP project.

See https://github.com/firebase/firebase-functions/pull/1370 for another description of the problem.

Surprisingly, I wasn't able to find the discussion of this limitation in public GCP docs - I'll see if this limitation still exists in the platform and try to find related documentation on it.

**Comment by taeold** [comment] 2024-07-18 16:51
Ah the limitation is indirectly discussed here:

https://cloud.google.com/functions/quotas#resource_limits

Note that the behavior when the event is >10MB is "drop and log" - will ask if they plan on updating the doc to include that caveat.

**Comment by exaby73** [comment] 2024-08-15 16:48
Based on @taeold's comment above, this is working as intended. I'll close this issue

**Closed by exaby73** 2024-08-15 16:48 UTC
Labels: documentation
