### ISSUE TITLE
Missing log entries (on large console.log calls)

### ISSUE THREAD

**Issue by kitfit-dave** [firebase/firebase-functions#825] opened 2020-12-07 23:17 UTC
### Version info

**node:**

v10.18.1

**firebase-functions:**

3.12.0

**firebase-tools:**

8.4.3

### Test case

I have a function that logs some data and one of the log lines gets skipped. It is a line that is stringifying an object and I suspected it was getting omitted when that object is large, so I put a length check in there, it was 103021 chars.

Now, I agree that that is an unreasonable size to expect to go into the log, but previously, I believe large log entries were truncated. Now it seems they are skipped entirely.

### Steps to reproduce

try to do a console.log with 100000 characters in it

### Expected behavior

the line to be truncated at some reasonable number of characters

### Actual behavior

that whole log line will be omitted

### Were you able to successfully deploy your functions?

sure.

**Comment by inlined** [comment] 2021-03-01 21:13
I tried to reproduce the omitted log line with a 259K log line. The line came out a bit wonky because the JSON structure is visible (it's truncated so it doesn't correctly format the log), but the log line is still there. Closing as no repro, partially because this part of the backend was freshly edited and the bug may have been fixed.

As an FYI, the new log line limit is also 256KB per log line. You'll lose a bit of that padding with the `functions.logger` because we use JSON annotations to correctly set the severity.

**Closed by inlined** 2021-03-01 21:13 UTC
Labels: needs-triage
