### ISSUE TITLE
functions.auth.user().onCreate is not triggering on new Firebase Authentication user.

### ISSUE THREAD

**Issue by jamie-chapman** [firebase/firebase-functions#595] opened 2019-12-16 17:29 UTC
Firebase functions version 3.3.0

Node version v10.13.0

Firebase version 7.10.0

Create a cloud function with firebase auth user onCreate trigger, it does not trigger at all, expecting it to trigger on creation of a new auth user and run my cloud function.

The function deploys correctly but does not fire.

**Comment by andrianabeltran** [comment] 2019-12-16 18:49
Hello, thanks for submitting your issue. Can you please provide answers to all the required questions? Thanks!

**Comment by jamie-chapman** [comment] 2019-12-17 09:15
Updated my original comment with answers to the required questions :)

**Comment by andrianabeltran** [comment] 2019-12-17 21:46
@jamie-chapman 
1. Do you mind sharing your steps / code to reproduce this? 
2. What region is your function deployed to? We have an internal issue being tracked that's affecting europe-west1 region. (internal tracking: 145502073)

Thanks!

What region is your function deployed to? We have

**Comment by SEGVeenstra** [comment] 2019-12-22 11:38
> 1. Do you mind sharing your steps / code to reproduce this?
> 2. What region is your function deployed to? We have an internal issue being tracked that's affecting europe-west1 region. (internal tracking: 145502073)

I'm experiencing the same on us-central1.

```
export const createProfile = functions.auth.user().onCreate((user) => {
    return admin.firestore().collection('users').doc(user.uid).set({
    });
});
```
The just `firebase deploy --only functions`

Deployment is successful but it never gets triggered.
I'm testing it with the same account that I delete from firebase.

Hope that helps.

**Comment by SEGVeenstra** [comment] 2019-12-30 06:41
What more information is needed?

**Comment by andrianabeltran** [comment] 2020-01-03 21:57
Hello, we are still working to fix the issue for US central 1. We'll update you with more progress on our end

**Comment by svhen** [comment] 2020-01-04 16:23
Hi, i'm facing a similar issue, the function is executed, but sometimes the users collection is updated and sometimes not, i'm using in front the follow function:

Front work
`export const signUp = newUser => {
  return (dispatch, getState, { getFirebase, getFirestore }) => {
    const firestore = getFirestore();
    firebase
      .createUser(
        {
          email: newUser.email,
          password: newUser.password
        },
        {
          firstName: newUser.firstName,
          lastName: newUser.lastName,
          initials: newUser.firstName[0] + newUser.lastName[0],
          email: newUser.email,
          streetCoins: 10
        }
      )
      .then(_ => {      
        const user = firebase.auth().currentUser;  
        
        if (user) {
          firestore
            .collection("users")
            .doc(user.uid)
            .update({
              userId: user.uid
            })
            .then(_ => {
              dispatch({ type: "SIGNUP_SUCCESS" });
            });
        }

      })
      .catch(err => {
        dispatch({ type: "SIGNUP_ERROR", err });
      });
  };
};`

In cloud functions sometimes work:

`export default functions.auth.user().onCreate(async (user) => {
  const customer = await stripe.customers.create({ email: user.email });
  return await 
      admin
        .firestore()
        .collection("users")
        .doc(user.uid)
        .update({
          customer_id: customer.id
        });
});`

I don't know if is a code issue or a cloud firestore issue, thanks!

**Comment by kernelpop** [comment] 2020-01-04 18:05
I'm also seeing intermittent failures on two functions performing Firestore add() operations.

```
7.5.0/firebase-app.js"
7.5.0/firebase-auth.js"
7.5.0/firebase-firestore.js"
7.5.0/firebase-functions.js"
```

About 2 minutes after a failed invocation I receive two log message:

1:
`Unhandled rejection`

2:
```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/srv/node_modules/google-auth-library/build/src/auth/googleauth.js:159:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by adsonrocha** [comment] 2020-01-16 20:06
I am also having problems with the onCreate trigger. It is not been called. Here is my code:

    exports.myFunction = functions.database.ref('/collection/{id}').onCreate((snapshot, context) => {
      const a= snapshot.val();
      return admin.firestore().doc('other/'+o.id).set({
        // data...
      }).then(function () {
        console.log('Successfully created other');
      }).catch(function (error) {
        console.log('Error creating other:', error);
      });
    });

**Comment by jamie-chapman** [comment] 2020-01-29 09:45
> Hello, thanks for submitting your issue. Can you please provide answers to all the required questions? Thanks!

Hi, so it's

> @jamie-chapman
> 
> 1. Do you mind sharing your steps / code to reproduce this?
> 2. What region is your function deployed to? We have an internal issue being tracked that's affecting europe-west1 region. (internal tracking: 145502073)
> 
> Thanks!

Hi,

So steps to reproduce would be to create a function that triggers with Firebase Authentication. The region is europe-west1.

**Comment by brunocrosier** [comment] 2020-02-12 16:11
I'm having the same issue.. deployed to us-central1 but the function is never called

**Comment by brunocrosier** [comment] 2020-02-12 16:33
To anybody experiencing this issue, here is the solution:

The reason you **cannot** do something like 

```javascript
exports.handleNewSignups = functions.auth.user().onCreate(async user => {
  const { uid, displayName, email } = user

  return await admin
    .firestore()
    .collection("users")
    .set({ user })
})
```

is because the `user` object causes an error - you can see this in the Firebase dashboard at Functions > Logs

```
Couldn't serialize object of type "UserRecordMetadata" (found in field "metadata"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
```

Instead something like this will work:

```javascript
exports.handleAuth = functions.auth.user().onCreate(async user => {
  const { uid, displayName, email } = user

  return await admin
    .firestore()
    .collection("users")
    .doc(uid)
    .set({ uid, displayName, email })
})
```

We essentially just extract the `uid, displayName, email` fields off of the user and use only those ones to create the new user document, thereby avoiding the object inside `user.metadata`

**Comment by SEGVeenstra** [comment] 2020-02-13 08:41
> To anybody experiencing this issue, here is the solution:
> 
> The reason you **cannot** do something like
> 
> ```js
> exports.handleNewSignups = functions.auth.user().onCreate(async user => {
>   return await admin
>     .firestore()
>     .collection("users")
>     .set({ user })
> })
> ```
> 
> is because the `user` object causes an error - you can see this in the Firebase dashboard at Functions > Logs
> 
> ```
> Couldn't serialize object of type "UserRecordMetadata" (found in field "metadata"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
> ```
> 
> Instead something like this will work:
> 
> ```js
> exports.handleNewSignups = functions.auth.user().onCreate(async user => {
>   const { uid, displayName, email } = user
> 
>   return await admin
>     .firestore()
>     .collection("users")
>     .doc(uid)
>     .set({ uid, displayName, email })
> })
> ```
> 
> We essentially just extract the `uid, displayName, email` fields off of the user and use only those ones to create the new user document, thereby avoiding the object inside `user.metadata`

This is about wrong implementation.
The issue is that the function just isn't called. If I put in just a `print()` nothing happens

**Comment by SEGVeenstra** [comment] 2020-03-03 11:11
I just tried this again by letting someone else create a new account. It still doesn't trigger. Is this gonna be fixed or what?

**Comment by andrianabeltran** [comment] 2020-03-19 20:22
@jamie-chapman Sorry for the delay - we need your project name, region and function name of a function with a recent failure. In order to trace the failure, it needs to be recent since the server logs deletes them after a while

**Comment by jamie-chapman** [comment] 2020-03-20 10:17
@andrianabeltran Hi, sorry I cannot be of more help but this hasn't happened to me for some months now. Perhaps someone else on this thread has however?

**Comment by mpomarole** [comment] 2020-03-27 09:06
I am seeing the same here by just following the code in the firebase docs: https://firebase.google.com/docs/auth/admin/custom-claims

I create the user and the functions trigger never gets called.

**Comment by Pushplaybang** [comment] 2020-04-04 01:12
I"m also experiencing this, it seems to be limited to social auth, I'm only using google, while email and phone auth seem to be fine.

**Comment by mbleigh** [comment] 2020-04-05 13:52
This issue is best served by contacting Firebase support -- if a function
is deployed but not triggering that's an issue in the backend and not
something that can be addressed in the SDK.

**Comment by aner87** [comment] 2020-06-18 12:29
> > To anybody experiencing this issue, here is the solution:
> > The reason you **cannot** do something like
> > ```js
> > exports.handleNewSignups = functions.auth.user().onCreate(async user => {
> >   return await admin
> >     .firestore()
> >     .collection("users")
> >     .set({ user })
> > })
> > ```
> > 
> > 
> > is because the `user` object causes an error - you can see this in the Firebase dashboard at Functions > Logs
> > ```
> > Couldn't serialize object of type "UserRecordMetadata" (found in field "metadata"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
> > ```
> > 
> > 
> > Instead something like this will work:
> > ```js
> > exports.handleNewSignups = functions.auth.user().onCreate(async user => {
> >   const { uid, displayName, email } = user
> > 
> >   return await admin
> >     .firestore()
> >     .collection("users")
> >     .doc(uid)
> >     .set({ uid, displayName, email })
> > })
> > ```
> > 
> > 
> > We essentially just extract the `uid, displayName, email` fields off of the user and use only those ones to create the new user document, thereby avoiding the object inside `user.metadata`
> 
> This is about wrong implementation.
> The issue is that the function just isn't called. If I put in just a `print()` nothing happens

Actually there is a way to save the whole Object without losing some info.
That's how I ended up implementing it:

`const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.saveNewUser = functions.auth.user().onCreate(async user => {
    return admin
    .firestore()
    .collection('users')
    .doc(user.uid)
    .set(JSON.parse(JSON.stringify(user)));
  })`

**Comment by czmarcos** [comment] 2020-08-25 22:50
@aner87 solution solved my problem using firebase auth onCreate trigger with cloud functions. thanks!

**Comment by crossan007** [comment] 2021-04-05 18:47
I think I'm seeing this issue in the local functions emulator.

I have a function in my `index.js` file:
```
exports.handleNewUser = functions.auth.user().onCreate(async (user) => {
  console.log("Hey, new user");
});
``` 
and the emulator logs show that the function should be running:
```
emulators: Starting emulators: functions
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub
+  functions: Using node@12 from host.
!  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to c:\<REDACTED>.json. Non-emulated services will access production using these credentials. Be careful!
!  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "c:\<REDACTED>\functions" for Cloud Functions...
!  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
+  functions[handleNewUser]: auth function initialized.
```

When I create a new user in my app's Firebase Auth page (non-emulated), I expected to see `Hey, new user` in my emulated console, but nothing happens.

I'm not 100% sure that the issue is in firebase functions; this issue also looks possibly related: https://github.com/firebase/firebase-tools/issues/2847

**Comment by mbleigh** [comment] 2021-04-05 18:58
@crossan007 emulated functions are not expected to trigger based on non-emulated events. If you want to test emulated `onCreate` functions you will need to start the auth emulator and create emulated users.

**Comment by crossan007** [comment] 2021-04-05 18:59
@mbleigh Oh, thanks!  I suppose I over-interpreted the scope of the emulator log line `!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub` 😅

**Comment by joehan** [comment] 2021-05-12 17:20
Hey all, I'm going to close this issue since its hasn't had any activity in a while. If you are experiencing something similar:
- If a function is successfully deployed but not triggering _at all_ when you expect it to, please contact Firebase Support. That is indicative of a backend issue.
- If the function is triggering but throwing errors or not successfully deploying, please open another issue and describe your problem.

**Closed by joehan** 2021-05-12 17:20 UTC
Labels: Needs: Attention, api: auth, type: bug

**Comment by vovahost** [comment] 2023-05-17 05:47
> 

You can now use `user.toJSON()`

**Comment by ve-varun-sharma** [comment] 2024-07-24 18:35
Just calling out here that we're still experiencing this issue with the Firebase Auth trigger not working. Region is us-central-1. We're also getting the non instances available error when we are only invoking the trigger once and max instance count is above 500.
![image](https://github.com/user-attachments/assets/ee1e9218-da54-4f27-93c4-e3b573ea61d2)


Firebase Authentication Trigger Feature ===> [The firebase community reaction here](https://www.youtube.com/watch?v=3dTF45dISYE)

**Comment by ve-varun-sharma** [comment] 2024-07-24 18:36
Just calling out here that we're still experiencing this issue with the Firebase Auth trigger not working. Region is us-central-1. We're also getting the non instances available error when we are only invoking the trigger once and max instance count is above 500.
![image](https://github.com/user-attachments/assets/08c14e55-c362-45fd-b97d-3c56272375e7)


Firebase Authentication Trigger Feature ===> [The firebase community reaction here](https://www.youtube.com/watch?v=3dTF45dISYE)

**Comment by saif97** [comment] 2025-02-16 00:04
Not sure if this is the reason, but I was accessing Firestore  `const db = getFirestore();` I changed it to `const db = admin.firestore();` Deployed & it worked.
