### ISSUE TITLE
Deploy fails when using post-install commands on Node16

### ISSUE THREAD

**Issue by m4recek** [firebase/firebase-functions#1362] opened 2023-03-16 19:28 UTC
**node:**
16

### [REQUIRED] Test case
package.json
{
	"engines": {
		"node": "16"
	},
	"scripts": {
		"postinstall": "patch-package"
	},
	"dependencies": {
		"patch-package": "~6.4.7",
	}
}

### [REQUIRED] Actual behavior
Try to deploy a function that is using any post-install command which comes from installed packages on Node 16

### [REQUIRED] Expected behavior
Function build should not run post-install command before packages are installed 

### Were you able to successfully deploy your functions?
No

**Comment by blidd-google** [comment] 2023-03-29 20:34
Hi @m4recek, I was unable to reproduce your issue — deploying your functions with `firebase deploy` should not run `npm install`. Can you provide a simple example so I can see what your error is? Thanks.

**Comment by m4recek** [comment] 2023-03-29 22:12
I am off until next week so I cant do minified example. 

The issue is not on the client side but on the server. Specifically in the Cloud Build which is running `Step #1 - "build": Running "npm install --package-lock-only --quiet"` which then runs post-install command from package.json.

<img width="1424" alt="Screenshot 2023-03-30 at 00 09 42" src="https://user-images.githubusercontent.com/1221226/228679040-206f0471-6292-4d87-983e-5b3bb1d2f528.png">

We have patched our deployments by amending post-install command with a check for `node-modules/patch-package` folder, if it does not exists (it wont for `npm install --package-lock-only`) then we exit the command.

**Comment by blidd-google** [comment] 2023-03-31 15:49
Got it, it looks like this is an issue with our Google Cloud dependencies and not with the firebase functions SDK; like you have already discovered, Cloud Build does indeed run `npm install` for Cloud Functions that use the Node.js runtime and your workaround should avoid the postinstall problem. I'm going to close this issue for now, but if you would still like to escalate this issue with the Google Cloud Functions team, you can file a bug with their [public issue tracker here](https://issuetracker.google.com/issues?q=status:open%20componentid:187195).

**Closed by blidd-google** 2023-03-31 15:49 UTC
Labels: Needs: Attention

**Comment by m4recek** [comment] 2023-03-31 17:52
No offense but... I will let google with ˜180k employees handle resending tickets to the correct teams or keep having issues with deployments on the flagship products.

**Comment by Blunderchips** [comment] 2024-11-16 13:23
> No offense but... I will let google with ˜180k employees handle resending tickets to the correct teams or keep having issues with deployments on the flagship products.

legend stays it still has not been assigned to the right team
