### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by brianmhunt** [firebase/firebase-functions#457] opened 2019-06-03 16:37 UTC
### [REQUIRED] Version info

**node:** 10

```
$ firebase --version
6.1.2
$ yarn list --pattern firebase
yarn list v1.15.2
├─ @firebase/app-types@0.3.10
├─ @firebase/app@0.3.17
├─ @firebase/database-types@0.3.11
├─ @firebase/database@0.3.20
├─ @firebase/logger@0.1.13
├─ @firebase/util@0.2.14
├─ firebase-admin@8.0.0
└─ firebase-functions@2.3.1
```

### [REQUIRED] Test case

Seems to be any Firestore function triggered on write.  Let me know if you cannot reproduce. 

### [REQUIRED] Steps to reproduce

A Firestore Trigger

![image](https://user-images.githubusercontent.com/135528/58818163-6d62fc80-85fb-11e9-896e-f1f42f4e71fe.png)

Per the stack trace, raises on line 136 of `node_modules/firebase-functions/lib/providers/firestore.js:136:75`:

![image](https://user-images.githubusercontent.com/135528/58818431-eeba8f00-85fb-11e9-8829-eb173fe91e02.png)

### [REQUIRED] Expected behavior

No error

### [REQUIRED] Actual behavior

> TypeError: Cannot read property 'name' of undefined     at beforeSnapshotConstructor (/srv/functions/node_modules/firebase-functions/lib/providers/firestore.js:136:75)     at changeConstructor (/srv/functions/node_modules/firebase-functions/lib/providers/firestore.js:142:49)     at cloudFunctionNewSignature (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:119:34)     at cloudFunction (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:151:20)     at Promise.resolve.then (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28)     at process._tickCallback (internal/process/next_tick.js:68:7) |  
-- | --

### Were you able to successfully deploy your functions?
Yes

**Comment by thechenky** [comment] 2019-06-03 17:12
Hi @brianmhunt this is the same issue as https://github.com/firebase/firebase-functions/issues/447. I'm working on a fix, but please follow that bug. Thanks for your patience.

**Comment by thechenky** [comment] 2019-06-03 17:22
Duplicate of https://github.com/firebase/firebase-functions/issues/447

**Closed** 2019-06-03 17:23 UTC
Labels: api: firestore
