### ISSUE TITLE
Error on configure trigger "providers/firebase.auth/eventTypes/user.create"

### ISSUE THREAD

**Issue by elzenso** [firebase/firebase-functions#741] opened 2020-07-17 06:30 UTC
### [REQUIRED] Version info

**node:** 10.21.0
**firebase-functions:** 3.8.0
**firebase-tools:** 8.1.1
**firebase-admin:** 9.0.0

### [REQUIRED] Test case

Following function:
```import * as functions from 'firebase-functions';
import { setCustomUserClaim } from './user-claims';

const runtimeOpts: functions.RuntimeOptions = {
    timeoutSeconds: 30,
    memory: '128MB'
}

export const OnUserCreate = functions.runWith(runtimeOpts)
    .region("asia-northeast1") 
    .auth.user().onCreate(async user => {
        try {
            await setCustomUserClaim(user)
        } catch (err) {
            console.error(`failed to auth because of ${err}`)
        }
    });
```
throws `Failed to configure trigger providers/firebase.auth/eventTypes/user.create@firebaseauth.googleapis.com` error ~~after moving from node 8 to node 10.~~ without any reason.

### [REQUIRED] Steps to reproduce

deploy functions using: ```firebase deploy --debug --only firestore,functions```

### [REQUIRED] Actual behavior
[firebase.log](https://github.com/firebase/firebase-functions/files/4936072/firebase.log)

### [REQUIRED] Expected behavior
It should deploy properly.

**Comment by arxeiss** [comment] 2020-07-17 09:08
@elzenso I have the same problem, but it is **not** related to Node changes. Everything worked fine earlier this week. Now it is not working. I made no changes at all.

I'm uploading 5 functions. First is HTTP trigger, next 3 of them are regular triggers listening on documents and last one is `.auth.user().onCreate()`. 4 functions are deployed successfully but 5th one is always failing. It is not possible for me to deploy same version of function as I did few days ago.


```
✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing packages/functions directory for uploading...
i  functions: packaged packages/functions (21.35 KB) for uploading
✔  functions: packages/functions folder uploaded successfully
i  functions: updating Node.js 10 function onUserCreated(europe-west1)...
i  functions: updating Node.js 10 function onWorkspaceCreated(europe-west1)...
i  functions: updating Node.js 10 function addUserToWorkspace(europe-west1)...
i  functions: updating Node.js 10 function onUserDeletedFromWorkspace(europe-west1)...
i  functions: updating Node.js 10 function onWorkspaceDeleted(europe-west1)...
✔  functions[onUserDeletedFromWorkspace(europe-west1)]: Successful update operation. 
⚠  functions[onUserCreated(europe-west1)]: Deployment error.
Failed to configure trigger providers/firebase.auth/eventTypes/user.create@firebaseauth.googleapis.com (__gcf__.europe-west1.onUserCreated)
✔  functions[onWorkspaceDeleted(europe-west1)]: Successful update operation. 
✔  functions[onWorkspaceCreated(europe-west1)]: Successful update operation. 
✔  functions[addUserToWorkspace(europe-west1)]: Successful update operation. 
```

**Comment by bhr** [comment] 2020-07-17 09:25
Same issue here. I can confirm the issue is **not** related to updating to Node 10. I just re-deployed the same function without any changes and it shows the same error as above.

From the Firebase console:
```
{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"Failed to configure trigger providers/firebase.auth/eventTypes/user.create@firebaseauth.googleapis.com (__gcf__.europe-west1.auth-onCreate)"},"authenticationInfo":{"principalEmail":"xyz@gmail.com"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/<#myproj#>/locations/europe-west1/functions/auth-onCreate"}
--
```

**Comment by elzenso** [comment] 2020-07-17 11:12
Yes, I can confirm too it's not related to node 10 after tried to rollback the function.

**Comment by ecclestonjbp** [comment] 2020-07-17 11:13
I'm experiencing the exact same issue.  No node upgrade has been performed, and deployments of the same codebase were working yesterday (2020-07-16):
Error is:
`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"Failed to configure trigger providers/firebase.auth/eventTypes/user.create@firebaseauth.googleapis.com (__gcf__.europe-west2.createUserRecord)"},"authenticationInfo":{"principalEmail":"REDACTED"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/REDACTED/locations/europe-west2/functions/createUserRecord"} `
and I see something very similar for a delete user trigger:
`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"Failed to configure trigger providers/firebase.auth/eventTypes/user.delete@firebaseauth.googleapis.com (__gcf__.europe-west2.cleanUpDeletedUser)"},"authenticationInfo":{"principalEmail":"REDACTED"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/REDACTED/locations/europe-west2/functions/cleanUpDeletedUser"}`

**Comment by arxeiss** [comment] 2020-07-17 11:18
Developers are probably working on this. Now it passed for me locally from my computer and also from CI. :partying_face: :champagne:

**Comment by mbleigh** [comment] 2020-07-17 15:59
Hi, this is a GCF backend issue affecting some of the newer launched regions -- the team is working on it and it should be functional again later today. Since this isn't an SDK issue I'm going to go ahead and close this.

**Closed by mbleigh** 2020-07-17 15:59 UTC
Labels: needs-triage

**Comment by binhodev** [comment] 2020-07-31 03:15
Hello, i have the same problem...

```
firebase deploy --only functions:OrderStatusChanged

=== Deploying to 'lojavirtualteste-1bce6'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /Users/binho/Projetos/loja_virtual/functions
> tslint --project tsconfig.json


WARNING: /Users/binho/Projetos/loja_virtual/functions/src/index.ts:321:5 - Expected a 'for-of' loop instead of a 'for' loop with this simple iteration

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /Users/binho/Projetos/loja_virtual/functions
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (41.64 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: current functions in project: OrderStatusChanged(us-central1), authorizeCreditCard(us-central1), cancelCreditCard(us-central1), captureCreditCard(us-central1), onNewOrder(us-central1)
i  functions: uploading functions in project: OrderStatusChanged(us-central1)
i  functions: updating Node.js 10 function OrderStatusChanged(us-central1)...
⚠  functions[OrderStatusChanged(us-central1)]: Deployment error.
Failed to configure trigger providers/cloud.firestore/eventTypes/document.update@firestore.googleapis.com (__gcf__.us-central1.OrderStatusChanged)


Functions deploy had errors with the following functions:
        OrderStatusChanged


To try redeploying those functions, run:
    firebase deploy --only functions:OrderStatusChanged


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```

**Comment by chrisime** [comment] 2021-01-09 19:02
This issue is happening again: when I try to deploy my firebase functions be it with _nodejs 10_ or  _nodejs 12_ I got the same error message. 
region is **nam5 (us-central)**
@mbleigh I'd ask you to re-open the ticket and re-investigate, thanks!

**Comment by mbleigh** [comment] 2021-01-12 20:58
@chrisime I don't think it's likely to be related to the original issue here. I'd recommend reaching out to [Firebase support](https://firebase.google.com/support/troubleshooter/contact) with details about your project id and debug logs.

**Comment by chrisime** [comment] 2021-01-12 21:04
@mbleigh the issue is gone now, no idea whatever happened, thanks :-)

**Comment by caplis** [comment] 2021-01-29 03:11
Came across this issue after creating a new project for a sandbox. Enabling an authentication method fixed it for us. Our bad for missing the auth method, but the messaging could be better.

**Comment by chrisime** [comment] 2021-01-29 07:51
> Came across this issue after creating a new project for a sandbox. Enabling an authentication method fixed it for us. Our bad for missing the auth method, but the messaging could be better.

indeed, this would be very helpful!
@mbleigh ^^
