### ISSUE TITLE
Error in emulated function: Provided authentication credentials for the app named "[DEFAULT]"

### ISSUE THREAD

**Issue by gerhardcit** [firebase/firebase-functions#99] opened 2017-09-02 11:06 UTC
### Version info

**firebase-functions:*^0.6.2*

**firebase-tools:*3.10.0*

**firebase-admin:*~5.2.1*

node: 6.11.2

### Test case

Somehow a DEFAULT is stuck when I start a new project for firebase serve --only functions
It seems like firebase functions is stuck with a reference from a previous project somewhere.
Setting a blank new code project and a new firebase project I cannot get it to update the database.

This error keeps popping up:
```
error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. 
```

However, on a fresh machine, it all works ok.

### Steps to reproduce

Initialize a basic functions project (in a new firebase project)

index.js
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

exports.helloWorld = functions.https.onRequest((request, response) => {
    return response.send("Hello " + request.query.name || 'No one');
});

exports.helloWrite = functions.https.onRequest((request, response) => {
    admin.database().ref("/test/x1").set({ 
        hi: request.query.name || "there",
        date: new Date().toISOString()
    }, function (err) {
        if (err) console.log(err);
        return response.send("Hello " + request.query.name || 'No one');
    });
});

```

Serve it
```
firebase serve --only functions
```

Test it
```
curl -X GET 'http://localhost:5000/live-test-49290/us-central1/helloWorld?name=Steve'
Hello Steve
```
All is good

Test the write
```
curl -X GET 'http://localhost:5000/live-test-49290/us-central1/helloWrite?name=Steve'

error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.
```
NOT so good here..

.firebaserc
```
{
  "projects": {
    "default": "live-test-49290"
  }
}
```

When I try to get a config
```
firebase functions:config:get
{}
```

I have multiple firebase logins and multiple projects in each login.
Have tried firebase logout and firebase login

**Comment by gerhardcit** [comment] 2017-09-02 12:58
This seems to have something to do with having  @google-cloud/functions-emulator installed.
on 2 machines where NO functions-emulator is installed, all is working well.
In the one with it, I get the error above.
@laurenzlong, is there something we should know about firebase serve and functions-emulator that would save us from spending days of debugging?

**Comment by laurenzlong** [comment] 2017-09-11 18:36
Sorry about this! This was a bug in the CLI that was affecting deploys as well as emulation. Should have been fixed in v3.10.1 (https://github.com/firebase/firebase-tools/releases/tag/v3.10.1). Please reopen the issue if it's still there after updating firebase-tools.

**Comment by wuservices** [comment] 2017-10-02 15:14
@laurenzlong I just started trying out Firebase a couple days ago, and I'm getting this error:
> error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.

Not sure if it's quite the same, but I get the error immediately after starting the local emulator.

This minimal code seems to trigger the message to come up over and over once the emulator starts:
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);
const db = admin.database();

exports.test = functions.https.onRequest((req, res) => {
  res.send('Hello world');
});
```

I've uninstalled a few times and re-installed and tried linking the master repo, but it still seems to happen.

For now, I've just been manually adding credentials to run the local emulator, but that's not supposed to be needed with Firebase, right?

Workaround
```
const serviceAccount = require('./serviceAccountKey.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'https://....firebaseio.com',
  storageBucket: '....appspot.com'
});
```

While I am new to the Firebase stuff, I probably had some gcloud stuff on my machine already, and that's authed to a completely different user and project.

**Comment by laurenzlong** [comment] 2017-10-02 16:05
I think you have an outdated version of firebase-tools. Can you update it by running:
npm install -g firebase-tools

**Comment by wuservices** [comment] 2017-10-02 16:12
I think I'm on the latest. I've reinstalled with the command you gave me just in case and I'm still on 3.12.0.
```
~/project-id$ firebase -V
3.12.0
~/project-id$ firebase serve --only functions

=== Serving from '/Users/jon/project-id'...

i  functions: Preparing to emulate functions.
Warning: You're using Node.js v8.6.0 but Google Cloud Functions only supports v6.11.1.
✔  functions: test: http://localhost:5000/project-id/us-central1/test
✔  functions: injestEmailNotifications: http://localhost:5000/project-id/us-central1/test
✔  functions: ingestEmailNotifications: http://localhost:5000/project-id/us-central1/test
error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.
```

**Comment by laurenzlong** [comment] 2017-10-02 16:18
Can you run these inside your project's root directory?

rm .firebaserc
firebase use --add

Then follow the prompt to link your project again.

**Comment by wuservices** [comment] 2017-10-02 16:43
Thanks for the quick reply. I tried those commands and that still didn't work.

Feedback unrelated to this issue: During `firebase use --add`, it feels weird to ask me to enter an alias as a first time Firebase user with only 1 project. Perhaps it should just default to something so you could hit enter if you didn't care or know why it mattered yet.

**Comment by wuservices** [comment] 2017-10-02 17:20
I also noticed that I had `GOOGLE_APPLICATION_CREDENTIALS` set for another project, but removing that from my environment and redoing everything didn't seem to change things. I also tried `gcloud auth revoke --all`, which I saw in another issue. That didn't help either.

**Comment by laurenzlong** [comment] 2017-10-02 17:39
Can you paste your new logs?

**Comment by wuservices** [comment] 2017-10-02 17:55
They're the same. Here's the whole process:

```
~/my-project-id$ firebase -V
3.12.0
~/my-project-id$ rm .firebaserc
~/my-project-id$ firebase use --add
? Which project do you want to add? my-project-id
? What alias do you want to use for this project? (e.g. staging) prod

Created alias prod for my-project-id.
Now using alias prod (my-project-id)
~/my-project-id$ firebase serve --only functions

=== Serving from '/Users/jon/my-project-id'...

i  functions: Preparing to emulate functions.
Warning: You're using Node.js v8.6.0 but Google Cloud Functions only supports v6.11.1.
✔  functions: test: http://localhost:5000/my-project-id/us-central1/test
error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.
error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.
```
... (over and over and over)

**Comment by aneudy1702** [comment] 2017-10-30 18:33
@laurenzlong  thank your helping with this. I can confirm I am on @3.13.1 and I am getting the exact same error.

**Comment by giacomodeglinnocenti** [comment] 2017-11-15 16:10
Same problem here on

```
Air-di-Giacomo:functions jack$ sudo npm list -g firebase-tools
Password:
/usr/local/lib
└── firebase-tools@3.14.0 
```

and just update on 

`└─┬ firebase-tools@3.15.0 `

and still getting

`error: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project. `

on

`admin.initializeApp(functions.config().firebase);`

(I've also already done 

`firebase functions:config:get > .runtimeconfig.json`

before launch 

`firebase experimental:functions:shell`

**Comment by laurenzlong** [comment] 2017-11-16 00:34
@aneudy1702 and @giacomodeglinnocenti, can you update everything to the latest version by running the following command inside of the functions directory? (not the project root)

```
npm install -g firebase-tools@latest
npm install --save firebase-functions@latest
npm install --save firebase-admin@5.5.0
``` 

And modify your `functions/index.js` to also print out what `functions.config().firebase` is. After running `firebase experimental:functions:shell`, it should print something like:

```
 { databaseURL: 'https://my-project.firebaseio.com',
  storageBucket: 'my-project.appspot.com',
  apiKey: 'someKey',
  authDomain: 'my-project.firebaseapp.com',
  projectId: 'my-project',
  credential: 
   ApplicationDefaultCredential {
     credential_: RefreshTokenCredential { refreshToken_: [Object] } } }

```

**Comment by aneudy1702** [comment] 2017-11-16 22:26
@laurenzlong I have updated my modules as you suggest and I do get an object printed out that resembles the one you shared. Yet, I am still getting the same error.

**Comment by laurenzlong** [comment] 2017-11-16 22:46
@aneudy1702 can you share a screenshot? firebase-admin 5.5.0 does not have the error line "Provided authentication credentials for the app named..." in its source code so it is strange that you're still getting that error. And can you double check that your functions/package.json says `~5.5.0` next to `firebase-admin`?

**Comment by aneudy1702** [comment] 2017-11-16 22:55
<img width="908" alt="screen shot 2017-11-16 at 5 53 17 pm" src="https://user-images.githubusercontent.com/4418589/32920432-32262108-caf7-11e7-94ec-10bd6fa1139f.png">


and this is part of my package.json

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "aws-sdk": "^2.141.0",
    "ejs": "^2.5.7",
    "firebase-admin": "^5.5.0",
    "firebase-functions": "^0.7.3",
    "lodash": "^4.17.4",
    "moment-timezone": "^0.5.13",
    "nodemailer": "^4.3.1",
    "nodemailer-ses-transport": "^1.5.1"
  },
  "private": true
}
```

I have already removed my node_modules and retried and even my package-lock shows the new version

**Comment by laurenzlong** [comment] 2017-11-16 23:09
Thanks for sharing, this is getting very puzzling, and I appreciate all of your help. I have a few more questions:
- What aspects of the admin SDK are you trying to use after initializing it? Messaging? Database? Can you share lines of code?
- When you printed out `functions.config().firebase`, was `[DEFAULT]` in there somewhere? Did it have the correct project ID?

**Comment by laurenzlong** [comment] 2017-11-17 19:51
Can you try running:
```
cat ~/.config/gcloud/application_default_credentials.json # let me know if there isn't such file for you
# if there is such a file:
rm ~/.config/gcloud/application_default_credentials.json
```
Then try `firebase experimental:functions:shell` again.

**Comment by aminelaadhari** [comment] 2017-11-20 09:10
@laurenzlong we have the same issue, and we tried everything you suggested without any success.

**Comment by aminelaadhari** [comment] 2017-11-20 09:35
Also, I think the warning should be an error. All functions are timing out and we weren't able to detect that using Stackdriver because they are warnings and not errors.

**Comment by laurenzlong** [comment] 2017-11-20 19:26
@aminelaadhari Are you running into this issue in production or with the emulator? What firebase-functions version are you using? And how are you initializing the app? And how are you using it in your code?

**Comment by aminelaadhari** [comment] 2017-11-20 19:40
@laurenzlong in prodcution

**Comment by laurenzlong** [comment] 2017-11-20 19:48
@aminelaadhari That seems to be a different issue then, since this issue is about locally emulated functions. Can you file a separate issue, and include all the information asked for by the template, as well as my questions above?

**Comment by smkhalsa** [comment] 2017-11-22 02:17
@laurenzlong I'm getting this as well in production. I'm using the latest libraries for admin and functions.

Has a separate issue been opened for this issue in production?

**Comment by laurenzlong** [comment] 2017-11-22 19:18
@smkhalsa please file one.

**Comment by laurenzlong** [comment] 2017-11-27 23:13
@aneudy1702 Please reopen this issue if my recommendations in https://github.com/firebase/firebase-functions/issues/99#issuecomment-345348808 do not work.

**Closed by laurenzlong** 2017-11-27 23:13 UTC

**Comment by michaelfreund** [comment] 2017-12-04 16:31
@laurenzlong as @wuservices mentioned in an earlier comment, try removing env var `GOOGLE_APPLICATION_CREDENTIALS` if set. That at least solved the problem for me.

**Comment by Vani-gurnani** [comment] 2017-12-13 16:20
Hello,

I am having the same issue on Google Cloud Functions. I am getting following error in Google Cloud (NOT EMULATOR). 
FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project. 

My Package.json has these dependencies
"firebase-admin": "^5.5.1",
"firebase-functions": "^0.7.3"

I also tried following suggestion in [#99 Comment](https://github.com/firebase/firebase-functions/issues/99#issuecomment-345348808)

**Comment by laurenzlong** [comment] 2017-12-15 04:13
@Vani-gurnani What features of firebase-admin are you trying to access? Currently admin.auth doesn't work.

**Comment by stewburnell** [comment] 2018-08-03 01:36
@michaelfreund unsetting GOOGLE_APPLICATION_CREDENTIALS worked for me. I had tried everything else prior. Thanks.

**Comment by goelmk** [comment] 2018-09-16 14:32
Following worked for me:

npm install -g firebase-tools@latest
npm install --save firebase-functions@latest
npm install --save firebase-admin@latest
