### ISSUE TITLE
Error: Argument "data" is not a valid Document. Input is not a plain JavaScript object

### ISSUE THREAD

**Issue by kamlesh-bambarde** [firebase/firebase-functions#326] opened 2018-10-01 15:05 UTC
error on creating new document using 

```
var obj = JSON.parse(JSON.stringify(req.body));
firebaseHelper.firestore.createNewDocument(db, userCollection, obj);


config---

    "firebase": "^5.3.0",
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.0.5",
    "firebase-functions-helper": "^0.5.10"

```

Error: Argument "data" is not a valid Document. Input is not a plain JavaScript object.
    at Validator.(anonymous function).err [as isDocument] (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/validate.js:99:27)
    at CollectionReference.add (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:1683:25)
    at FirestoreHelper.createNewDocument (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:35:39)
    at /user_code/index.js:251:4
    at Layer.handle [as handle_request] (/user_code/node_modules/express/lib/router/layer.js:95:5)
    at next (/user_code/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/user_code/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/user_code/node_modules/express/lib/router/layer.js:95:5)
    at /user_code/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/user_code/node_modules/express/lib/router/index.js:335:12)

**Comment by laurenzlong** [comment] 2018-10-03 00:04
Duplicate of https://github.com/googleapis/nodejs-firestore/issues/213 Please comment on it with your issue. It probably helps if you can print out req.body and provide it in your comment.

**Closed by laurenzlong** 2018-10-03 00:04 UTC

**Comment by laurenzlong** [comment] 2018-10-03 00:06
Also `firebase-functions-helper` is not an official Google product. Please try to repro the issue using firebase-admin.
