### ISSUE TITLE
Cloud Functions 400 Bad Request with invalid JSON in hello world app

### ISSUE THREAD

**Issue by hmagdy** [firebase/firebase-functions#364] opened 2018-12-25 22:47 UTC
### Version info

**firebase-functions:** 6.2.2

### Test case and Steps to reproduce

I have hello world cloud functions app, it's working fine either locally by firebase serve or online after firebase deploy

```
const functions = require('firebase-functions');
exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});
```

Locally I can open http://localhost:5000/testing-98b0b/us-central1/helloWorld without any issues, but if I use postman to send post call with an invalid body like "#" it crashes and keep loading with below error:

enter image description here
```
error: { SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/usr/local/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/usr/local/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/json.js:83:15)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:224:16)
    at done (/usr/local/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  expose: true,
  statusCode: 400,
  status: 400,
  body: '#',
  type: 'entity.parse.failed' }
```

Also after firebase deploy I can open https://us-central1-staff-testing-98b0b.cloudfunctions.net/helloWorld without any issues but if I use postman to send post call with an invalid body like "#" it crashes and returns 400 bad request with below error:

enter image description here
```
SyntaxError: Unexpected token # in JSON at position 0
    at Object.parse (native)
    at createStrictSyntaxError (/var/tmp/worker/node_modules/body-parser/lib/types/json.js:157:10)
    at parse (/var/tmp/worker/node_modules/body-parser/lib/types/json.js:83:15)
    at /var/tmp/worker/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/var/tmp/worker/node_modules/raw-body/index.js:224:16)
    at done (/var/tmp/worker/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/var/tmp/worker/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

### Expected behavior
It should handle this type of error.

### Actual behavior
crash locally and 400 bad request online

**Comment by thechenky** [comment] 2018-12-27 20:47
@hmagdy are you supplying the correct Content-Type headers? The headers is how the SDK determines how to parse the data. See https://firebase.google.com/docs/functions/http-events#read_values_from_the_request. Curling works for me with a POST: 

```
curl -X POST -H "Content-Type: text/plain" -d "hi" https://us-central1-staff-testing-98b0b.cloudfunctions.net/helloWorld`
```

**Comment by thechenky** [comment] 2018-12-27 20:49
Also, if I change the headers to `"Content-Type: application/json"` for the same request it returns 400 Bad Request in the same way you described.

**Comment by thechenky** [comment] 2018-12-28 18:48
Closing this out since this is working as intended. Free to open another issue if you encounter any other problems. Thanks!

**Closed by thechenky** 2018-12-28 18:48 UTC
Labels: http
