### ISSUE TITLE
Legacy compat API of firebase-admin 11.x breaks Cloud Functions for Firebase

### ISSUE THREAD

**Issue by milosmns** [firebase/firebase-functions#1282] opened 2022-10-27 11:28 UTC
### [READ] Step 1: Are you in the right place?

I think so, yes.

### [REQUIRED] Step 2: Describe your environment

**[See my previous report](https://github.com/firebase/firebase-functions/issues/1278)** on Firebase Functions for details about my environment. Since then, I have updated my TS version to `4.6.4`, which fixed the errors I initially had with Admin SDK. But now I have a fresh set of errors.

  * Operating System version: GH Actions image + macOS Monterey 12.5.1
  * Firebase Product: database, functions
  * Firebase SDK version: 11 ([see more](https://github.com/firebase/firebase-functions/issues/1278))
  * Node.js version: 16 ([see more](https://github.com/firebase/firebase-functions/issues/1278))
  * NPM version: 8 ([see more](https://github.com/firebase/firebase-functions/issues/1278))

The problem I'm reporting started happening after I updated Admin from `10.3.0` to `11.2.0`.

#### Steps to reproduce:

It looks like initialization of Firebase Admin fails on launch. This happens both with `serve` and `deploy --only functions`. TSC and Lint pass fine without any issues.

Here's the console output with `--debug`:

```console
[2022-10-27T11:19:49.312Z] Building nodejs source
[2022-10-27T11:19:49.312Z] Analyzing nodejs backend spec
[2022-10-27T11:19:49.319Z] Could not find functions.yaml. Must use http discovery
[2022-10-27T11:19:49.450Z] Serving at port 9007

[2022-10-27T11:19:49.568Z] Got response from /__/functions.yaml Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'create')
[2022-10-27T11:19:49.570Z] Failed to parse functions.yamlincomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 60:
     ...  from function source: TypeError: Cannot read properties of unde ... 
                                         ^ {"name":"YAMLException","reason":"incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line","mark":{"name":null,"buffer":"Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'create')\n\u0000","position":59,"line":0,"column":59},"message":"incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 60:\n     ...  from function source: TypeError: Cannot read properties of unde ... \n                                         ^"}
[2022-10-27T11:19:49.583Z] shutdown requested via /__/quitquitquit

⬢  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'create') {"metadata":{"emulator":{"name":"functions"},"message":"Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'create')"}}
```

#### Relevant Code:

This is how I initialize the SDK now:

```ts
import * as functions from "firebase-functions";
import * as firebaseAdmin from "firebase-admin";

firebaseAdmin.initializeApp();

...
```

In another file I also have the following, but I don't think my run ever reaches that stage to require the file to run.

```ts
import * as firebaseAdmin from "firebase-admin";

private static database = firebaseAdmin.database();

...
```

#### What have I tried:

- Googling, StackOverflowing, etc.
- [This advice](https://github.com/firebase/firebase-admin-node/issues/1856#issuecomment-1208479760), even though the official documentation does not reflect it. It doesn't fix the issue for me
- Reverting back to v10, which works but is not a solution to this problem

### Priority

From my POV it's high priority because the functions won't launch, but not urgent.
I can give more code/information if needed.

_cc @cryptonikki @erakoviczoran_

**Comment by milosmns** [comment] 2022-10-27 19:47
Ok. I mean I don't mind, any help is appreciated... but I was fairly sure that admin sdk initialization was the one failing.

Thanks for checking!

**Comment by inlined** [comment] 2022-10-31 19:00
We've noticed some issues using the deprecated "compat" interface within firebase functions. To get unblocked while we research fixes, try

```
import { initializeApp } from "firebase-admin/app";
import { getDatabase } from "firebase-admin/database";

initializeApp();
const db = getDatabase(/* can optionally pass the return value of initializeApp */);
```

**Comment by milosmns** [comment] 2022-10-31 23:36
@inlined thanks for the suggestion, I just tried it out. Now I see my linter failing.
Note: I could totally be doing something really dumb and be unaware of it.

> Run cd functions && npm run lint
  cd functions && npm run lint
  shell: /usr/bin/bash -e {0}

> lint
> eslint --ext .js,.ts .

/home/runner/work/***-tooling/***-tooling/functions/src/index.ts
  2:31  error  Unable to resolve path to module 'firebase-admin/app'  import/no-unresolved

/home/runner/work/***-tooling/***-tooling/functions/src/storage/storage.ts
  1:29  error  Unable to resolve path to module 'firebase-admin/database'  import/no-unresolved

✖ 2 problems (2 errors, 0 warnings)

Error: Process completed with exit code 1.

**Comment by StormyDragon** [comment] 2022-11-02 14:34
`TypeError: Cannot read properties of undefined (reading 'create')`
It was caused by attempting to instantiate an `axios` client. `"axios": "^1.1.3",`

```ts
import axios from 'axios'
const client = axios.create()
```

**Comment by milosmns** [comment] 2022-11-02 16:03
@inlined it looks like the lint issue is this one: https://stackoverflow.com/a/69959606/2102748 - Solved ✅
The original issue is still present, which seems now to be unrelated to Firebase SDK upgrades.

But you may be right @StormyDragon, I do have `axios` as well (although in different files, required only later). I'll investigate this angle now, thanks for the hint.

**Comment by milosmns** [comment] 2022-11-02 16:18
Verified, the bug is gone if I simply downgrade `axios` to `v0.27.2`.

**Comment by taeold** [comment] 2022-11-02 18:10
@milosmns Thanks for sharing your updates! Looks like we can close the issue for now - I'll reach out to admin sdk to see if breaking `const { initializeApp } = require("firebase-admin")` was intentional in v11.

**Closed by taeold** 2022-11-02 18:10 UTC
Labels: api: database
