### ISSUE TITLE
Cloud functions not deploying

### ISSUE THREAD

**Issue by SeanOThomas** [firebase/firebase-functions#618] opened 2020-01-24 03:12 UTC
### Related issues

https://github.com/firebase/functions-samples/issues/478

### [REQUIRED] Version info

**node:**

v12.4.0

**firebase-functions:**
^3.1.0

**firebase-tools:**

7.12.1

**firebase-admin:**

^8.0.0"

### [REQUIRED] Steps to reproduce

Run `firebase deploy`

Functions should deploy

Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

```
[debug] [2020-01-23T19:52:22.903Z] ----------------------------------------------------------------------
[debug] [2020-01-23T19:52:22.905Z] Command:       /usr/local/Cellar/node/12.4.0/bin/node /usr/local/bin/firebase deploy
[debug] [2020-01-23T19:52:22.905Z] CLI Version:   7.12.1
[debug] [2020-01-23T19:52:22.905Z] Platform:      darwin
[debug] [2020-01-23T19:52:22.905Z] Node Version:  v12.4.0
[debug] [2020-01-23T19:52:22.907Z] Time:          Fri Jan 24 2020 08:52:22 GMT+1300 (New Zealand Daylight Time)
[debug] [2020-01-23T19:52:22.907Z] ----------------------------------------------------------------------
[debug] [2020-01-23T19:52:22.907Z] 
[debug] [2020-01-23T19:52:22.917Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-01-23T19:52:22.917Z] > authorizing via signed-in user
[debug] [2020-01-23T19:52:22.917Z] [iam] checking project gith-fe4e6 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2020-01-23T19:52:22.919Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/gith-fe4e6:testIamPermissions  

[debug] [2020-01-23T19:52:23.484Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'gith-fe4e6'...
[info] 
[info] i  deploying functions
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script.
[debug] [2020-01-23T19:52:31.690Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/firestore": "^2.6.0",
    "@google-cloud/storage": "^4.1.3",
    "@google/maps": "^1.0.2",
    "@types/fs-extra": "^8.0.1",
    "@types/google__maps": "^0.5.8",
    "@types/sharp": "^0.23.0",
    "@types/uuid": "^3.4.6",
    "child-process-promise": "^2.2.1",
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.1.0",
    "fs-extra": "^8.1.0",
    "mkdirp-promise": "^5.0.1",
    "sharp": "^0.23.3",
    "typed-promisify": "^0.4.0",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2020-01-23T19:52:31.691Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/gith-fe4e6/services/cloudfunctions.googleapis.com  
 
[debug] [2020-01-23T19:52:31.692Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/gith-fe4e6/services/runtimeconfig.googleapis.com  
 
[debug] [2020-01-23T19:52:33.386Z] <<< HTTP RESPONSE 200
[debug] [2020-01-23T19:52:33.438Z] <<< HTTP RESPONSE 200
[info] ✔  functions: all necessary APIs are enabled
[debug] [2020-01-23T19:52:33.439Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/gith-fe4e6/adminSdkConfig  
 
[debug] [2020-01-23T19:52:34.075Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2020-01-23T19:52:34.078Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/gith-fe4e6/configs  
 
[debug] [2020-01-23T19:52:34.816Z] <<< HTTP RESPONSE 200
[error] 
[error] Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.
[debug] [2020-01-23T20:03:22.300Z] ----------------------------------------------------------------------
[debug] [2020-01-23T20:03:22.302Z] Command:       /usr/local/Cellar/node/12.4.0/bin/node /usr/local/bin/firebase deploy
[debug] [2020-01-23T20:03:22.302Z] CLI Version:   7.12.1
[debug] [2020-01-23T20:03:22.302Z] Platform:      darwin
[debug] [2020-01-23T20:03:22.302Z] Node Version:  v12.4.0
[debug] [2020-01-23T20:03:22.304Z] Time:          Fri Jan 24 2020 09:03:22 GMT+1300 (New Zealand Daylight Time)
[debug] [2020-01-23T20:03:22.304Z] ----------------------------------------------------------------------
[debug] [2020-01-23T20:03:22.304Z] 
[debug] [2020-01-23T20:03:22.312Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-01-23T20:03:22.313Z] > authorizing via signed-in user
[debug] [2020-01-23T20:03:22.313Z] [iam] checking project gith-fe4e6 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2020-01-23T20:03:22.314Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/gith-fe4e6:testIamPermissions  

[debug] [2020-01-23T20:03:24.247Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'gith-fe4e6'...
[info] 
[info] i  deploying functions
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script.
[debug] [2020-01-23T20:03:32.768Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/firestore": "^2.6.0",
    "@google-cloud/storage": "^4.1.3",
    "@google/maps": "^1.0.2",
    "@types/fs-extra": "^8.0.1",
    "@types/google__maps": "^0.5.8",
    "@types/sharp": "^0.23.0",
    "@types/uuid": "^3.4.6",
    "child-process-promise": "^2.2.1",
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.1.0",
    "fs-extra": "^8.1.0",
    "mkdirp-promise": "^5.0.1",
    "sharp": "^0.23.3",
    "typed-promisify": "^0.4.0",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2020-01-23T20:03:32.769Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/gith-fe4e6/services/cloudfunctions.googleapis.com  
 
[debug] [2020-01-23T20:03:32.769Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/gith-fe4e6/services/runtimeconfig.googleapis.com  
 
[debug] [2020-01-23T20:03:34.485Z] <<< HTTP RESPONSE 200
[debug] [2020-01-23T20:03:34.541Z] <<< HTTP RESPONSE 200
[info] ✔  functions: all necessary APIs are enabled
[debug] [2020-01-23T20:03:34.542Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/gith-fe4e6/adminSdkConfig  
 
[debug] [2020-01-23T20:03:35.307Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2020-01-23T20:03:35.309Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/gith-fe4e6/configs  
 
[debug] [2020-01-23T20:03:36.020Z] <<< HTTP RESPONSE 200
[error] 
[error] Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.
[debug] [2020-01-24T03:06:32.649Z] ----------------------------------------------------------------------
[debug] [2020-01-24T03:06:32.651Z] Command:       /usr/local/Cellar/node/12.4.0/bin/node /usr/local/bin/firebase deploy
[debug] [2020-01-24T03:06:32.652Z] CLI Version:   7.12.1
[debug] [2020-01-24T03:06:32.652Z] Platform:      darwin
[debug] [2020-01-24T03:06:32.652Z] Node Version:  v12.4.0
[debug] [2020-01-24T03:06:32.653Z] Time:          Fri Jan 24 2020 16:06:32 GMT+1300 (New Zealand Daylight Time)
[debug] [2020-01-24T03:06:32.653Z] ----------------------------------------------------------------------
[debug] [2020-01-24T03:06:32.653Z] 
[debug] [2020-01-24T03:06:32.661Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-01-24T03:06:32.661Z] > authorizing via signed-in user
[debug] [2020-01-24T03:06:32.661Z] [iam] checking project gith-fe4e6 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2020-01-24T03:06:32.663Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/gith-fe4e6:testIamPermissions  

[debug] [2020-01-24T03:06:33.103Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'gith-fe4e6'...
[info] 
[info] i  deploying functions
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script.
[debug] [2020-01-24T03:06:40.199Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/firestore": "^2.6.0",
    "@google-cloud/storage": "^4.1.3",
    "@google/maps": "^1.0.2",
    "@types/fs-extra": "^8.0.1",
    "@types/google__maps": "^0.5.8",
    "@types/sharp": "^0.23.0",
    "@types/uuid": "^3.4.6",
    "child-process-promise": "^2.2.1",
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.1.0",
    "fs-extra": "^8.1.0",
    "mkdirp-promise": "^5.0.1",
    "sharp": "^0.23.3",
    "typed-promisify": "^0.4.0",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2020-01-24T03:06:40.200Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/gith-fe4e6/services/cloudfunctions.googleapis.com  
 
[debug] [2020-01-24T03:06:40.201Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/gith-fe4e6/services/runtimeconfig.googleapis.com  
 
[debug] [2020-01-24T03:06:41.782Z] <<< HTTP RESPONSE 200
[debug] [2020-01-24T03:06:41.836Z] <<< HTTP RESPONSE 200
[info] ✔  functions: all necessary APIs are enabled
[debug] [2020-01-24T03:06:41.837Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/gith-fe4e6/adminSdkConfig  
 
[debug] [2020-01-24T03:06:42.380Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2020-01-24T03:06:42.382Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/gith-fe4e6/configs  
 
[debug] [2020-01-24T03:06:42.978Z] <<< HTTP RESPONSE 200
[error] 
[error] Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

```

### Were you able to successfully deploy your functions?

Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

**Comment by SeanOThomas** [comment] 2020-01-24 03:40
I fixed the issues by updating all packages.

**Comment by tinaliang** [comment] 2020-01-28 18:30
Closing this since the issue is fixed

**Closed by tinaliang** 2020-01-28 18:30 UTC
Labels: needs-triage

**Comment by akivab** [comment] 2020-02-23 09:23
Saw the same issue with outdated version of sharp, updating the package seems to fix.
