### ISSUE TITLE
While Testing Firebase httpsCallable functions Firebase Client giving "FirebaseError: internal" Error

### ISSUE THREAD

**Issue by Rohit1024** [firebase/firebase-functions#1411] opened 2023-06-01 09:22 UTC
### Related issues

I  have asked a similar question in stackOverflow : [**Question**](https://stackoverflow.com/q/76379302/20239914)

### Version info :

**node: 16**

**firebase-functions: ^4.2.0**

**firebase-tools: 11.30.0**

**firebase-admin: ^11.5.0**

### Steps to reproduce and Test case : 
 1. Run `firebase init` to initialize the Firebase Configurable. Then select `Functions` and `Emulators`.
 2. For Emulators select Functions emulator and ui emulator. Then for Functions emulator assign port as `5001` and for ui assign port as `2000`.
 3. For Functions select typescript and let firebase download the dependencies. Then paste the following code in `functions/index.ts` : 
```js
import * as functions from "firebase-functions";

export const helloWorld = functions.https.onCall((data, context) => {
    console.log(data);
    return { success : true };
});
```
4. Run `npm run build` inside the `functions/` folder to build the function. Then start the firebase emulator using `firebase emulators: start` 
5. Now initialize a new project by installing firebase sdk and initializing the SDK with firebaseConfig as follows **index.ts**: 
```js
import { initializeApp } from "firebase/app";
import { connectFunctionsEmulator, getFunctions, httpsCallable } from "firebase/functions";

const firebaseConfig = { /*...firebaseConfig*/ };

const app = initializeApp(firebaseConfig);
const functions = getFunctions(app);
const useEmulator:boolean = true

if(useEmulator) {
    connectFunctionsEmulator(functions, "localhost", 5001);
}

const triggerCallable = httpsCallable(functions, "helloWorld");
const result = await triggerCallable({
    message : "Hello world",
    count: 1
});
console.log(result); // expected : { success : true }
``` 
6. Run the `index.ts` file with `npm run build && node dist/index.js`, you will get : 
```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[FirebaseError: internal] {
  code: 'functions/internal',
  customData: undefined,
  details: undefined
}
```
> I am not even getting the function intialized message in the emulator logs. Although I do get `✔  functions: Loaded functions definitions from source: helloWorld.`

It looks like the function is not even initializing it correctly. I have also tried with `onCall()` 2nd gen firebase functions and it too has the same result `FirebaseError: internal`

### [REQUIRED] Expected behavior
I should get `{ success : true }` as a result printed in the console.

### [REQUIRED] Actual behavior
```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[FirebaseError: internal] {
  code: 'functions/internal',
  customData: undefined,
  details: undefined
}
```

### Were you able to successfully deploy your functions?
Yes This is working fine in production means when deployed to firebase I can able to call to the firebase function when `useEmulator` set to `false` making the firebase sdk to hit production.

**Comment by christhompsongoogle** [comment] 2023-06-01 18:57
Also filed today: 
https://stackoverflow.com/questions/76379302/while-testing-firebase-httpscallable-functions-firebase-client-giving-firebasee

**Comment by inlined** [comment] 2023-06-03 00:00
Since neither Kiana nor I can reproduce your error using your code, I'm going to close this issue as not reproducible. It seems you're a major version of firebase-tools behind. Try upgrading firebase-tools to get the latest version of the functions emulator. If that doesn't work, [Firebase Support](https://firebase.google.com/support) is appropriately staffed for these kinds of issues

**Closed by inlined** 2023-06-03 00:00 UTC
Labels: api: http, reproduceable: no, request-type: support
