### ISSUE TITLE
V2 Functions - Container Healthcheck failed.

### ISSUE THREAD

**Issue by viewee22** [firebase/firebase-functions#1394] opened 2023-05-15 01:22 UTC
### Related issues

[Error] V2 functions deployment fails with error in cloud run container service container fails to start #1131
https://github.com/firebase/firebase-functions/issues/1131

### [REQUIRED] Version info

**node:**

v18.14.0

**firebase-functions:**

4.3.1

**firebase-tools:**

9.20.0

**firebase-admin:**

11.8.0

### [REQUIRED] Test case

Cloud Storage trigger quickstart: Thumbnail generator
https://github.com/firebase/functions-samples/blob/python-ci/Node/quickstarts/thumbnails/functions/index.js

### [REQUIRED] Steps to reproduce

I tried above quickstart tutorial.

### [REQUIRED] Expected behavior

Deploy the gen2 firebase cloud function successefully and error free

### [REQUIRED] Actual behavior

![image](https://github.com/firebase/firebase-functions/assets/107836827/188d7f06-4f6e-4368-83ea-2374417ef78f)

### Were you able to successfully deploy your functions?
no

**Comment by viewee22** [comment] 2023-05-15 02:23
I solved it. The reason was that I did not install the sharp package from the functions folder, but from the project folder.

**Comment by taeold** [comment] 2023-05-15 18:43
@viewee22 Thank you for coming back and helping us shed light into your issue. I'm closing the issue for now, but feel free to open up a new one if you have any other problem.

**Closed by taeold** 2023-05-15 18:43 UTC
Labels: needs-triage

**Comment by Ladam0203** [comment] 2024-06-01 10:27
Hey! To anyone who stumbles upon this: this can be also caused by the package not matching your functions' node level. I had my local node to be >20 so my sharp package was working with the emulator, but not when I deployed. Turns out my functions' node engine was 16 which was not supported by the version of the sharp package I was using.

If you cannot set your functions' node level high enough, try updating your firebase cli global install.
