### ISSUE TITLE
500 Server Error at random times with random subset of functions and cloud function logs empty.

### ISSUE THREAD

**Issue by dsg38** [firebase/firebase-functions#816] opened 2020-11-24 20:45 UTC
### Related issues

https://stackoverflow.com/questions/60975200/firebase-http-cloud-function-500-server-error-try-again
https://issuetracker.google.com/issues/117181234
https://stackoverflow.com/questions/62269389/cloud-functions-responds-with-500-but-firebase-logs-empty

### [REQUIRED] Version info

**node:** 
v10.20.1

**firebase-functions:** 
3.11.0

**firebase-tools:**
8.16.2

**firebase-admin:**
9.3.0

### [REQUIRED] Test case

A **random subset** of my ~120 deployed cloud functions fail at **random times** with a 500 server error. There is **no trace in the cloud function logs** of these status 500 failed invocations:

```
<title>500 Server Error</title>
</head>

<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body>
```

I have a cron job running that pings each of the functions to check they are still reachable on the following schedule:

- every 5 minutes, every day, between 11:00 UTC and 04:00 UTC.

In just the past few hours these are the counts of the the number of functions that are reporting 500 errors (I've dropped out the rows when zero fail). Don't want to read too much into this, but it does look like there's a pattern with failures occurring on the hour and for a couple of subsequent 5 min intervals, before things return to normal:

```
createdDatetime,numFail
2020-11-24 14:00:18.624000+00:00,1
2020-11-24 15:05:16.452000+00:00,67
2020-11-24 15:10:19.521000+00:00,62
2020-11-24 16:00:38.829000+00:00,21
2020-11-24 16:05:24.326000+00:00,80
2020-11-24 16:10:16.677000+00:00,74
2020-11-24 17:00:26.638000+00:00,6
2020-11-24 17:05:27.180000+00:00,77
2020-11-24 17:10:24.747000+00:00,73
2020-11-24 18:00:54.138000+00:00,1
2020-11-24 18:05:22.029000+00:00,73
2020-11-24 18:10:24.093000+00:00,73
2020-11-24 19:00:44.363000+00:00,6
2020-11-24 19:05:23.759000+00:00,83
2020-11-24 19:10:19.689000+00:00,80
2020-11-24 20:00:53.804000+00:00,1
2020-11-24 20:05:20.530000+00:00,88
2020-11-24 20:10:23.785000+00:00,88
```

The issuetracker issue I reference above has been closed with the google employee stating that this is expected behaviour. NB: They imply that this is due to rapid scaling up - **this is not happening in my case** - we have very low level usage across all of these functions.

In one of the stackoverflow comments, Doug Stevenson says "...I suggest simply ramping up your load more slowly and see if that helps.". Do you think this is the issue? If so, how would I implement this when the function usage is driven by our app users?

There has been no outage / downtime reported in the firebase or GCP status for cloud functions at those times (as far as I know).

### [REQUIRED] Expected behavior

Functions not to randomly fail at random times with 500 error.

These failed executions to show up as errors in the logs.

### [REQUIRED] Actual behavior

Functions randomly fail at random times with 500 error.

These failed executions do not show up as errors in the logs.

### Were you able to successfully deploy your functions?

Yes

**Comment by dsg38** [comment] 2020-12-10 15:47
Response from Firebase Support:

> The engineering team found that the most likely root cause of this issue is that the requests are timing out in our infrastructure due to a widespread overload event. Based on your cron job which runs every 5 minutes,  it's likely that some set of your versions will still be cached after 5m of idle time when the request arrives, and will serve successfully. Because the cell you send traffic to at a given moment happens to be overloaded, functions without cached instances will not be able to obtain resources to start, and will time out.

> The workaround for this issue would be to configure client-side retries for these requests. It's possible that you could further experience better behavior by triggering functions not on-the-hour (e.g. trigger at 5:01:30, 5:06:30 instead of 5:00:00, 5:05:00) - but again, configuring retries would be the best way to mitigate this.

> Finally, it’s worth mentioning that we are aware these errors are not currently logged, and are working on implementing log messages when these errors occur. I don't think we have an ETA for when that will be available. I hope this analysis can help you to understand the root cause of the functions error. If you have any questions, feel free to write back.

I have responded to see if, in addition to fixing the logs, the engineering team have any plans to expand the infrastructure to prevent the root cause overload event.

**Comment by mcarriere** [comment] 2020-12-15 16:17
We're also experiencing this issue. We only started to notice it in the past few weeks. Happens on random functions and there's nothing about the execution in the logs. We have low traffic.

node:
10 and 12

firebase-functions:
3.13.0

firebase-admin:
9.4.2

**Comment by dsg38** [comment] 2020-12-18 16:27
Response from Firebase support to my follow up question regarding whether the engineering team have any plans to expand the infrastructure to prevent the root cause overload event in addition to fixing the logs:

> The functions team is focusing on improving the reliability of the service, this year Firebase released the new way functions build, this changes have brought a set of improvements that the team is working on, and they have added as a primary goal the improvement of the logs, and this critical 500 internal server errors are on the roadmap. 

> I don’t have an ETA for when these improvements will be released, but you can visit our official [blog](https://firebase.googleblog.com/), as well as our [release notes](https://firebase.google.com/support/releases) to keep an eye out for the latest features and bug fixes for Firebase.

**Comment by taeold** [comment] 2021-04-23 19:31
Thanks for sharing the info @dsg38.

As you suspect, this is a Google Cloud Functions issue and contacting support is the best way to get help. I'm also disappointed that the response doesn't seem to help with your problem. I'm closing the issue as the root cause isn't something Firebase Functions SDK can handle.

**Closed by taeold** 2021-04-23 19:31 UTC
Labels: needs-triage
