### ISSUE TITLE
Cannot read property 'seconds' of undefined

### ISSUE THREAD

**Issue by long1eu** [firebase/firebase-functions#922] opened 2021-07-28 18:41 UTC
### [REQUIRED] Version info

**node:** v14.16.0

**firebase-functions:** 3.14.1

**firebase-tools:** 9.16.0

**firebase-admin:** 9.11.0

### [REQUIRED] Test case

The crash happens randomly and looks like it's related to the code that invokes the functions. This is the stacktrace that I get:

```
TypeError: Cannot read property 'seconds' of undefined
    at Function.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:47)
    at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:677:57)
    at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:139:30)
    at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:143:49)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:133:34) 
```

My code is not even reached.

**Comment by long1eu** [comment] 2021-07-28 18:45
here you can see the logs

https://console.cloud.google.com/logs/query;query=labels.execution_id%3D%22szpg3xscguj7%22;timeRange=P7D;cursorTimestamp=2021-07-28T18:15:15.342254637Z?project=suppy-1bcd1

**Comment by aebischers** [comment] 2021-07-28 20:35
same issue here since July 28th 18:30 (UTC+2:00). Cloud Function and Firestore run on europe-west3.

"firebase-admin": "^8.13.0",
"firebase-functions": "^3.14.1",
    
TypeError: Cannot read property 'seconds' of undefined
at Function.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:116)
at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:539)
at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:139)
at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:143)
at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:133)
at Promise.resolve.then (invoker.js:199)
at process._tickCallback (next_tick.js:68)

**Comment by adamkoch** [comment] 2021-07-28 23:53
Seeing same issue as well (10 occurrences this morning). Recently updated node to 14 and also bumped firebase dependencies to latest:
```
    "firebase-admin": "^9.11.0",
    "firebase-functions": "^3.14.1",
```

Error:
```
TypeError: Cannot read property 'seconds' of undefined
    at Function.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:47)
    at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:685:57)
    at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:139:30)
    at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:143:49)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:133:34)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:199:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by uekkie** [comment] 2021-07-29 09:12
same issue here since July 29th 0:00 (UTC+9:00). Cloud Function and Firestore run on asia-northeast1.

```
firebase-admin@9.8.0
firebase-functions@3.14.1
```

Error: 
```
TypeError: Cannot read property 'seconds' of undefined
    at Function.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:47)
    at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:677:57)
    at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:139:30)
    at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:143:49)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:133:34)
```

**Comment by samruston** [comment] 2021-07-29 21:13
We're seeing thousands of these errors starting from ~ 1 hour ago. We're assuming something changed on the Firestore side as we haven't seen this error before and we haven't changed anything on our end.

**Comment by jgavazzisp** [comment] 2021-07-30 03:22
Hi there, the same problem with me, just got hundreds of thoughts of those errors in less than a few hours.

**Comment by MMDF** [comment] 2021-07-30 10:21
I've also experienced this issue with a firestore onUpdate hook about 16 times since yesterday. I've redeployed with the most recent versions of firebase libraries not sure if it is still here.

**Comment by long1eu** [comment] 2021-07-30 10:23
My issue is that we are very dependebt on cloud functions, and are users in production are affected by this. And no one is answering. This is lesson learned about cloud functions.

**Comment by MMDF** [comment] 2021-07-30 11:24
> My issue is that we are very dependebt on cloud functions, and are users in production are affected by this. And no one is answering. This is lesson learned about cloud functions.

This is happening on a critical cloud function and every time it fails, a user account is broken, so we have 16 users who can't use their accounts. There is no way for us to even know which accounts are broken as there is no log for which accounts it failed on.

**Comment by long1eu** [comment] 2021-07-30 11:31
Our situation is very similar. I would have move to cloud run, but guess
that, events are not supported there even though they have the scheme for
them.

**Comment by jakebiesinger-storyhealth** [comment] 2021-08-02 17:24
+1, we're seeing this in a bunch of our functions as of 9:40am Pacific. This is a major outage and no response from Google. 😢

**Comment by MerryOscar** [comment] 2021-08-02 17:40
Same issue. Any response from the Firebase team?

**Comment by long1eu** [comment] 2021-08-02 17:43
No response for us either.

**Comment by bcoe** [comment] 2021-08-02 17:51
👋 this issue just came to my attention through @jakebiesinger-storyhealth. I apologize that we missed triaging this, and that it's been affecting folks for several days.

I believe there's already [a fix](https://github.com/googleapis/nodejs-firestore/pull/1575) that was just landed.

Not 100% sure what the root cause was yet, we will update this thread with details.

**Comment by jakebiesinger-storyhealth** [comment] 2021-08-02 17:52
I opened a support ticket in GCP and gave them a call to try to light a fire. They say they'll respond within 1-2 hours... in the meantime, this a major outage for our services (where we use firestore processors for sending messages, processing workflow changes, etc)... we have tons of processor functions across many GCP projects, but are only seeing this error in a few of them. I assume there's some slow rollout that's causing your functions to fail as early as 5 days ago and ours to only start failing this morning.

**Comment by schmidt-sebastian** [comment] 2021-08-02 17:54
https://github.com/googleapis/nodejs-firestore/releases/tag/v4.14.1 is released and contains a change that should avoid hitting this codepath.

**Comment by jakebiesinger-storyhealth** [comment] 2021-08-02 17:59
Thanks for the fix. What isn't clear is why this suddenly started affecting us this morning. We haven't changed ANY of the code that runs in production in several days, yet somehow changes in this framework (not in our code and without an associated release on our side) led to a complete production outage 🤔 .

Should we expect our functions to "auto-update" and have our code start working again without an explicit release on our side? We've racked up thousands of failing invocations in the last hour alone.

**Comment by schmidt-sebastian** [comment] 2021-08-02 18:02
You have to update and re-deploy your functions. Make sure you have the latest version of `@google-cloud/firestore` when you do this - you probably have to re-install your dependencies.

I am not the right person to say why this started happening.

**Comment by jakebiesinger-storyhealth** [comment] 2021-08-02 18:10
Thanks for the info, @schmidt-sebastian. This is very strange... we last deployed on July 30th and have had thousands of executions since then...

**Comment by dgobaud** [comment] 2021-08-02 19:11
we are seeing this and it is bad - google support has no idea what is going on case 28641587

**Comment by jakebiesinger-storyhealth** [comment] 2021-08-02 19:20
I can confirm that redeploying with `"@google-cloud/firestore": "^4.14.1",` fixed the failure for us... but again, we haven't deployed in days so there's no explanation as to why the failure started in the first place, nor why only 4 out of several dozen firestore processors had the issue when we had many, many previous invocations.

![image](https://user-images.githubusercontent.com/66106280/127912324-481aa406-cd00-49be-b659-2dfedf1bea90.png)

**Comment by dgobaud** [comment] 2021-08-02 19:21
same thing it started randomly this morning 2021-08-02 09:40:36.291 PDT

impacting 3 functions

**Comment by liemdoan** [comment] 2021-08-02 19:22
Redploying with "@google-cloud/firestore": "^4.14.1" did not work for me.

**Comment by merlinnot** [comment] 2021-08-02 19:23
It also started happening in my projects, in ~45 Cloud Functions. Started at 16:40 UTC, all functions at a similar time. I didn't make any deployments at that time.

**Comment by merlinnot** [comment] 2021-08-02 19:26
I can confirm that updating `@google-cloud/firestore` to the latest version fixed an issue for at least some functions. Waiting for all deployment to finish, will report back.

**Comment by taeold** [comment] 2021-08-02 19:31
This issue is being treated with urgency by Google Cloud Platforms engineers. I'll share a link to official comms once that becomes available.

**Comment by dgobaud** [comment] 2021-08-02 19:33
@taeold status should be updated to say you have an outage / problem - your cloud support has no idea

**Comment by dgobaud** [comment] 2021-08-02 19:33
i redeployed with below - so far hasn't stopped happening

"@google-cloud/firestore": "^4.14.1"

**Comment by long1eu** [comment] 2021-08-02 19:37
Well I almost begged the customer support guy last Monday and he kept
asking me for a minimal example code that can reproduce the issue after I
pointed out numerous times the issue was with them according to the stack
trace.

I'm very very dissatisfied.

**Comment by dgobaud** [comment] 2021-08-02 19:41
@long1eu my experience firebase overall is very flaky compared to AWS Lambda unfortunately

**Comment by matthewtsmith** [comment] 2021-08-02 19:51
Our app is currently not functional due to this problem. I attempted the the fix posted [here](https://github.com/firebase/firebase-functions/issues/922#issuecomment-891275342) with no success.

**Comment by tamal-appsbee** [comment] 2021-08-02 19:55
Still same after updating "firebase-functions": "^3.14.1"
Please suggest a fix.

**Comment by merlinnot** [comment] 2021-08-02 20:05
Redeployed all functions with the fix, the issue is fully mitigated. Very curious to see a post mortem.

**Comment by matthewtsmith** [comment] 2021-08-02 20:09
@merlinnot Are you able to list your dependencies? Do you also import `firebase-functions`?

Previously I did not have `google-cloud/firestore` listed in our deps. I added it with no success.

**Comment by tamal-appsbee** [comment] 2021-08-02 20:12
After multiple deployment, still same issue:
=> "firebase-functions": "^3.14.1" (nodejs 10)
Using firestore triggers only

**Comment by merlinnot** [comment] 2021-08-02 20:13
I have `@google-cloud/firestore@4.14.1` and `firebase-functions@3.14.1`. Make sure you have both in `dependencies` and run `npm dedupe` to make sure that `firebase-functions` will use the top-level `@google-cloud/firestore`.

**Comment by taeold** [comment] 2021-08-02 20:17
For me, my dependency on `firebase-admin` automatically pulled in the latest version of `@google-cloud/firestore` which includes the fix. I'd make sure you nuke `package-lock.json` and `node_modules/` before trying the deploy.

**Comment by tamal-appsbee** [comment] 2021-08-02 20:32
Its working now
Thanks

**Comment by taeold** [comment] 2021-08-02 20:36
I see that GCP support team is no longer recommending the workaround of updating the `@google-cloud/firestore` to the latest. I see that several folks here have chimed in to say the workaround did work, but I'm not sure whether that's because of the updated package version or because of the rollback thats currently in progress. ETA for mitigation is set at 2021-08-02 17:30 US/Pacific.

**Comment by matmiad** [comment] 2021-08-02 21:06
Same issue here, happened in one project in the AM PST and then second project started seeing the same error PM PST. In the first project, updating `firebase-admin` and `@google-cloud/firestore` worked. Any links to status pages or google support? I do not see google official pages acknowledging any issues.

**Comment by mbleigh** [comment] 2021-08-02 21:28
Hi folks, this error seems to be affecting a small number of customers overall from what we've been able to glean. The Firestore backend team has completed a rollback that is suspected to be the root cause -- anyone who has been experiencing this issue, can you please report if it happens again? At this point we would not expect it to, even for unupdated SDKs.

**Comment by goleary** [comment] 2021-08-02 21:47
I'm still seeing the error in multiple environments as of seconds ago.

**Comment by mbleigh** [comment] 2021-08-02 23:10
@goleary thanks for the report -- I suspect the retries might be the issue here (we think some payloads might have been missing an expected internal timestamp). You may need to update your SDKs (as described earlier in this thread) to work through the retries for payloads missing the timestamp.

**Comment by goleary** [comment] 2021-08-02 23:48
@mbleigh Our project does not explicitly depend on `@google-cloud/firestore`. 

I updated `firebase-functions`, `firebase-admin` & `firebase-tools` to the latest versions, and redeployed but we continue seeing errors.

I also explicitly installed/deployed the latest version of `@google-cloud/firestore` (`4.14.1`) but we still continue receiving errors.

Is that what you are referring to or is there something else you suggest that I should try?

**Comment by liemdoan** [comment] 2021-08-02 23:51
@goleary I was experiencing the same issue. What I had to do is nuke the package-lock.json as suggested by @taeold and redeploy.

**Comment by demonar** [comment] 2021-08-03 01:03
confirmed that installing `@google-cloud/firestore` first in the list of dependencies and checking that replaces the existing dependency fixes the issue. @mbleigh the main `firebase-functions` library should be updated to use the new version of firestore to fix the issue completely though.

original version included with `firebase-functions` is `4.12.2`
after updating, the new version is `4.14.1`

**Comment by demonar** [comment] 2021-08-03 01:04
As a note, yes, on the project I'm working on we have retries enabled.

**Comment by goleary** [comment] 2021-08-03 02:27
> @goleary I was experiencing the same issue. What I had to do is nuke the package-lock.json as suggested by @taeold and redeploy.

This causes other issues.

I removed & readded `firebase-functions` & `firebase-admin` with the lockfile now referencing `@google-cloud/firestore@4.14.1` and yet the issue persists.

**Comment by dimavedenyapin** [comment] 2021-08-03 03:24
The issue still persists, I have retries enabled 
```
    "firebase-admin": "^9.11.0",
    "firebase-functions": "^3.14.1",
```

**Comment by PARADOXST** [comment] 2021-08-03 17:22
For those that use firebase function sdk, you could still experience function execution errors retry is enabled on the function. In this case please update the sdk version to the latest(3.14.1) (remember to delete the package-lock.json) and redeploy the function to resolve the issue.

**Comment by PARADOXST** [comment] 2021-08-03 18:23
@goleary Does the issue still persist? Can you paste a stacktrace of the failure?

**Comment by goleary** [comment] 2021-08-03 19:21
The issue persists.

I should note that we are using yarn, not npm.

This is taken from our `yarn.lock` file:

```
"@google-cloud/firestore@^4.14.1", "@google-cloud/firestore@^4.5.0":
  version "4.14.1"
  resolved "https://registry.yarnpkg.com/@google-cloud/firestore/-/firestore-4.14.1.tgz#c2692f4515d463bcf994981fad361a4690ecd6f3"
  integrity sha512-ecPxrwsk3IWfyILHhVtRJXFcn+CFnlYRbnM6vwS+eEwHAfSFoy4tNXlsvh7c4YihuojAkvgl4+iBxPMwy5X09A==
  dependencies:
    fast-deep-equal "^3.1.1"
    functional-red-black-tree "^1.0.1"
    google-gax "^2.17.1"
    protobufjs "^6.8.6"
```
Which looks dandy to me.

It does look like our stack trace is subtly different than the ones I see posted here in that the `@google-cloud/firestore` package is nested under `firebase-admin`...this seems like a problem.

Here is how they differ:
```diff
TypeError: Cannot read property 'seconds' of undefined
-   at Function.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:47)
+   at Function.fromProto (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:47)
-   at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:677:57)
+   at Firestore.snapshot_ (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:665:57)
    at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:139:30)
    at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:143:49)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:133:34)
  ```
  
I'll reiterate that entirely nuking our lock file caused other issues in our project that we wanted to avoid getting into which is why I removed and re-added all firebase packages (along with `@google-cloud/firestore@4.14.1`). From what I understand of our lockfile, we should have one top level `@google-cloud/firestore` package, but that is evidently not the case from the stacktrace.

**Comment by PARADOXST** [comment] 2021-08-03 20:23
@goleary I am fairly certain that your function runtime isn't using the 4.14.1 version you declared (you can verify it by applying some methods mentioned [here](https://stackoverflow.com/questions/29741373/check-package-version-at-runtime-in-nodejs)). And the fact that the diff points out the difference of the `@google-cloud/firestore` package location makes me realize that firebase-admin itself is pinning the version of `@google-cloud/firestore` as well, see my package-lock.json (this is after I pin the `@google-cloud/firestore` version in package.json and rerun `npm install`):
```
    "firebase-admin": {
      "version": "9.11.0",
      "resolved": "https://registry.npmjs.org/firebase-admin/-/firebase-admin-9.11.0.tgz",
      "integrity": "sha512-68fXdwcKF99LkWBE33M5hnLwjvGpbCRznIOtZVsiBqZdM9iwxlTfNEpAckh++o3GdJcSLRUWmIN+MKqPUsxoCA==",
      "requires": {
        "@firebase/database": "^0.10.0",
        "@firebase/database-types": "^0.7.2",
        "@google-cloud/firestore": "^4.5.0",
        "@google-cloud/storage": "^5.3.0",
        "@types/node": ">=12.12.47",
        "dicer": "^0.3.0",
        "jsonwebtoken": "^8.5.1",
        "jwks-rsa": "^2.0.2",
        "node-forge": "^0.10.0"
      }
    },
```
So please also update the `@google-cloud/firestore` version to be `4.14.1` and redeploy the function, and check if that works.
Also I am not sure how `"@google-cloud/firestore@^4.14.1", "@google-cloud/firestore@^4.5.0"` plays out in the yarn.lock file (not a yarn/npm expert myself, the version details seem to be right though), but maybe remove the old version from it as well just to make sure?

**Comment by goleary** [comment] 2021-08-03 20:25
It looks like after re-deploying (the same code/lockfile) some number of times the issue is resolved. I don't know if there was some sort of package cache that persisted between deployments or what, but we're all set for now, thanks for the suggestions @PARADOXST

**Comment by mbleigh** [comment] 2021-08-03 20:31
@goleary glad to hear it finally resolved, and sorry for the trouble! I'm going to close this out since I'm not aware of anyone still actively experiencing this issue. Please comment if anyone is still having problems.

**Closed by mbleigh** 2021-08-03 20:31 UTC
Labels: needs-triage

**Comment by magelikescoke** [comment] 2024-02-20 09:07
node: v20.9.0

firebase-functions: 4.4.1

firebase-admin: 11.11.0

**Comment by magelikescoke** [comment] 2024-02-20 09:07
The issue persists.

**Comment by inlined** [comment] 2024-03-04 23:53
@magelikescoke This is an entirely different codebase than the issue described in #1526 (JSON vs Protobuffer) so let's move the chat over there and not conflate bugs.
