### ISSUE TITLE
Body Does Not Exist on Type Request

### ISSUE THREAD

**Issue by vdiaz1130** [firebase/firebase-functions#977] opened 2021-09-18 01:15 UTC
### Related issues

I searched and could not find anything. Other thn this that is:
https://github.com/firebase/firebase-functions/issues/947#issuecomment-899651882

### [REQUIRED] Version info

**node:**
npm -v: 7.23.0
node -v: v14.17.5

"typescript": "^4.3.5"

**firebase-functions:**
firebase-functions: From package-lock.json:

**firebase-tools:**
firebase -V: 9.16.6

**firebase-admin:**
"firebase-admin": "^9.11.1",

### [REQUIRED] Test case

See screenshots

### [REQUIRED] Steps to reproduce

Create new project with versions mentioned. Paste this sample code:
```
import * as functions from 'firebase-functions';

export const test = functions.https.onRequest(async (req, res) => {
  console.log('req.body', req.body);
  res.send({});
});
```

### [REQUIRED] Expected behavior

No errors with req.body or res.send

### [REQUIRED] Actual behavior

Errors with req.body and res.send

### Were you able to successfully deploy your functions?

No. I'm suddenly getting these errors:
```
Property 'body' does not exist on type 'Request'
```
```
Property 'send' does not exist on type 'Response<any>'.
```
I'm importing from: 
```
import * as functions from 'firebase-functions';
```

Relevant imports from package.json
```
"@google-cloud/firestore": "^4.15.1",
"@google-cloud/language": "^4.3.1",
"@google-cloud/storage": "^5.14.2",
"@google-cloud/vision": "^2.4.0",
"express": "^4.17.1",
"firebase": "^9.0.2",
"firebase-admin": "^9.11.1",
"firebase-functions": "^3.15.6",
"@types/express": "4.17.2",
"@types/firebase": "^3.2.1",
"@types/node": "16.9.2",
"@types/request": "^2.48.7",
"ts-node": "^10.2.1",
"typescript": "~4.3.5"
```
![image](https://user-images.githubusercontent.com/24530571/133866976-a5749390-3cfd-42ee-bd13-df2135f37cfe.png)

![image](https://user-images.githubusercontent.com/24530571/133866985-d8ba9f67-0c0a-42b4-9f7e-d0a49dff2fc9.png)

Not sure if this is a bug or intentional but can't find a resolution.

**Comment by taeold** [comment] 2021-09-18 04:02
Hi @vdiaz1130, thanks for submitting the issue.

I cross checked the versions of the functions SDK and tried to locally reproduce the error without success.

When you hover over the `req` and `res` variable, what does your editor think its types are? For me, I see the following:

![Screen Shot 2021-09-17 at 9 01 19 PM](https://user-images.githubusercontent.com/14897098/133871858-988222f3-06bd-4cf5-af51-b074eecef21c.png)

![Screen Shot 2021-09-17 at 9 01 26 PM](https://user-images.githubusercontent.com/14897098/133871861-47582fd2-5598-4621-b3b5-18ba5b642ba0.png)

I wonder if the issue is visible only in your editor. Is your `tsc` command failing to compile your code? What does the error say there?

**Comment by vdiaz1130** [comment] 2021-09-18 04:09
Hello @taeold,

Pls see screensshots:
![image](https://user-images.githubusercontent.com/24530571/133871964-a4129f52-e4e2-4033-96ac-cd590d1ca0d9.png)

![image](https://user-images.githubusercontent.com/24530571/133871976-c8b5751e-b321-4578-bc32-0e6ec5c78344.png)

Code fails to compile:
![image](https://user-images.githubusercontent.com/24530571/133871988-e2fdd9cd-d7bf-4fca-9ad7-6cc95f5c08d0.png)

**Comment by vdiaz1130** [comment] 2021-09-18 05:11
![image](https://user-images.githubusercontent.com/24530571/133873122-c0dfe42f-61d1-4750-9bac-341d14e40048.png)

package-lock.json:
"firebase-functions": {
  "version": "3.15.6",
  "resolved": "https://registry.npmjs.org/firebase-functions/-/firebase-functions-3.15.6.tgz",
  "integrity": "sha512-VII8hV/jmg1L97SJrz7I0a4Heju4b2+4RxKBIcey5sU5pqV96acIjUOwn124GRZP9hStK36q8hm0W5s9lfQ3HQ==",
  "requires": {
    "@types/cors": "^2.8.5",
    "@types/express": "4.17.3",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "lodash": "^4.17.14"
  }
}

npm list:
~/projects/admin-app
├── @types/cors@2.8.12
├── @types/express@4.17.3
├── cors@2.8.5
├── express@4.17.1
├── lodash@4.17.21

// Firebase related
├── @angular/fire@7.0.4
├── @firebase/rules-unit-testing@1.3.15
├── @google-cloud/firestore@4.15.1
├── @google-cloud/language@4.3.1
├── @google-cloud/storage@5.14.2
├── @google-cloud/vision@2.4.0
├── @types/firebase@3.2.1
├── eslint-config-google@0.14.0
├── firebase-admin@9.11.1
├── firebase-functions-test@0.3.2
├── firebase-functions@3.15.6
├── firebase@9.0.2
├── passport-firebase-jwt@1.1.0

// Other
├── @types/node@16.9.2
├── express-serve-static-core@0.1.1
├── ts-node@10.2.1
├── tslib@2.3.1
├── typescript@4.3.5

**Comment by taeold** [comment] 2021-09-18 05:37
I wonder if https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138 is related.

Here are the versions `express` related type packages I'm using in my successful setup:

```
    "@types/express": {
      "version": "4.17.13",
      "resolved": "https://registry.npmjs.org/@types/express/-/express-4.17.13.tgz",
      "integrity": "sha512-6bSZTPaTIACxn48l50SR+axgrqm6qXFIxrdAKaG6PaJk3+zuUr35hBlgT7vOmJcum+OEaIBLtHV/qloEAFITeA==",
      "requires": {
        "@types/body-parser": "*",
        "@types/express-serve-static-core": "^4.17.18",
        "@types/qs": "*",
        "@types/serve-static": "*"
      }
    },
    "@types/express-serve-static-core": {
      "version": "4.17.24",
      "resolved": "https://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-4.17.24.tgz",
      "integrity": "sha512-3UJuW+Qxhzwjq3xhwXm2onQcFHn76frIYVbTu+kn24LFxI+dEhdfISDFovPB8VpEgW8oQCTpRuCe+0zJxB7NEA==",
      "requires": {
        "@types/node": "*",
        "@types/qs": "*",
        "@types/range-parser": "*"
      }
    },
```

Can you try out some of the suggestion from the thread and see if addresses your issue?

**Comment by vdiaz1130** [comment] 2021-09-18 06:47
@taeold, Thanks for the feedback. I switched from NPM to Yarn and followed this step:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138#issuecomment-632153679

I'm back up and running again - new issue with Firebase Auth signing in with email and password. Saving that one for tomorrow though. Thanks!

**Comment by taeold** [comment] 2021-09-20 03:25
@vdiaz1130 Good to hear - thanks for sharing your workaround.

I'm assuming that in the most project setup, dependencies for express type won't get mangled up. Going ahead and closing the issue.

**Closed by taeold** 2021-09-20 03:25 UTC
Labels: Needs: Attention
