### ISSUE TITLE
Preceding '/' in database trigger can cause context params to be empty

### ISSUE THREAD

**Issue by lhmatt** [firebase/firebase-functions#234] opened 2018-04-27 07:33 UTC
If the trigger path for the realtime database contains a preceding '/' then the context params will be empty. This could potentially be related to fixes implemented for #167.

### Version info

**firebase-functions:**
1.0.2

**firebase-tools:**
3.18.4

**firebase-admin:**
5.12.0

### Test case

`getPath()` simply returns a path with a preceding '/' e.g. `/v0/pendingEvents`

`export const process = functions.database.ref(`/${getPath()}/{newEventUID}`).onCreate((data, context) => {}`

So the actual trigger path ends up being `//v0/pendingEvents/{newEventUID}`

The path will trigger correctly but context.params will be empty; context.params.newEventUID will be undefined.

### Were you able to successfully deploy your functions?

Function deploys correctly, and the trigger is executed, but context.params is empty.

### Expected behavior

Up for debate, but ideally the deploy tools should warn about a double slash, even if it is handled by the SDK. I can't think of a situation where it you'd need a double slash in the trigger path.
Alternately, handle a double slash when parsing the context. However that's just hiding the actual problem.

**Comment by thechenky** [comment] 2018-12-18 22:01
Hi @lhmatt thanks for the feedback! This is already in our internal tracker - reference number 73455035. I'm going to close this out meanwhile as it's not a bug but more of an improvement and hopefully we'll get to it down the road.

**Closed by thechenky** 2018-12-18 22:01 UTC
Labels: realtime database
